microsoft/botframework-components

- skills/csharp/experimental/phoneskill/Services/BotServices.cs
After migrate to LuisV3, we should set PredictionOption explicitly to enable the _instance data visit.
adding                             PredictionOptions = new Microsoft.Bot.Builder.AI.LuisV3.LuisPredictionOptions() { IncludeInstanceData = true }
to enable the _instance data in LUIS result.
> [phone] Fixing issue when migrate to luisV3

- skills/declarative/calendarskill/calendarskill.dialog
- skills/declarative/calendarskill/dialogs/SearchMeetings/SearchMeetings.dialog
- skills/declarative/calendarskill/dialogs/TimeRemainingDialog/TimeRemainingDialog.dialog
- skills/declarative/calendarskill/dialogs/TimeRemainingDialog/language-generation/en-us/TimeRemainingDialog.en-us.lg
- skills/declarative/calendarskill/language-understanding/en-us/calendarskill.en-us.lu
- skills/declarative/calendarskill/settings/appsettings.json
Add time remaining flow in calendar skill
add time remaining luis and related flow.
> add time remaining flow

- skills/csharp/experimental/itsmskill/Dialogs/CloseTicketDialog.cs
- skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs
- skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs
- skills/csharp/experimental/itsmskill/Dialogs/UpdateTicketDialog.cs
- skills/csharp/experimental/itsmskill/Models/TicketsResult.cs
- skills/csharp/experimental/itsmskill/Responses/Shared/SharedResponses.cs
- skills/csharp/experimental/itsmskill/Services/ServiceNow/Management.cs
- skills/csharp/experimental/itsmskill/Services/ServiceNow/ServiceNowHelper.cs
- skills/csharp/tests/itsmskill.tests/API/Fakes/MockServiceNowRestClient.cs
The change enables logging out user when ServiceNow throws 401, this enables to get user out of the loop by implicitly logging him out.
Yes it is covered
> Implement Implicit User Logout on Unauthorized error

- skills/csharp/calendarskill/CalendarSkill.csproj
- skills/csharp/calendarskill/Dialogs/CalendarSkillDialogBase.cs
- skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
- skills/csharp/calendarskill/Dialogs/ShowEventsDialog.cs
- skills/csharp/calendarskill/Models/EventModel.cs
- skills/csharp/tests/calendarskill.tests/Flow/NextCalendarFlowTests.cs
close #189 
1. update MSGraph to 3.7
2. add online meeting link in CreateMeeting
3. provide the meeting link and phone number info in ShowMeeting
4. change "next meeting" behavior, show the detail card when there is just one event.
> [Calendar] add teams meeting link and show the infos

- skills/csharp/calendarskill/Deployment/Resources/LU/de-de/Calendar.lu
- skills/csharp/calendarskill/Deployment/Resources/LU/es-es/Calendar.lu
- skills/csharp/calendarskill/Deployment/Resources/LU/fr-fr/Calendar.lu
- skills/csharp/calendarskill/Deployment/Resources/LU/it-it/Calendar.lu
> [Calendar] remove prebuilt personName from de/it/fr/es calendar.lu

- skills/csharp/calendarskill/Dialogs/CreateEventDialog.cs
- skills/csharp/calendarskill/Dialogs/UpdateEventDialog.cs
- skills/csharp/calendarskill/Models/EventModel.cs
- skills/csharp/calendarskill/Utilities/CalendarCommonUtil.cs
fix and close:
https://github.com/microsoft/botframework-skills/issues/295
as the design before, all api calls use utc timezone. removed the utc timezone check and set user timezone when create/update meeting. keep the design of when get time from api calls it always returns utc time.
> [Calendar] fix displaying wrong timezone in outlook

- skills/declarative/calendarSkill/dialogs/CreateEventDialog/language-understanding/en-us/CreateEventDialog.en-us.lu
- skills/declarative/calendarSkill/dialogs/UpdateEventDialog/UpdateEventDialog.dialog
- skills/declarative/calendarSkill/dialogs/UpdateEventDialog/language-generation/en-us/UpdateEventDialog.en-us.lg
- skills/declarative/calendarSkill/dialogs/UpdateSlots/UpdateSlots.dialog
- skills/declarative/calendarSkill/dialogs/UpdateSlots/language-generation/en-us/UpdateSlots.en-us.lg
1. support accept/decline meeting when user attempt to update the meeting that user is not owner
2. update lg of UpdateSlotsDialog
3. remove some useless lu
> [Calendar v2] support accept/decline in update flow

- experimental/generator-adaptive-bot/generators/app/templates/dotnet/functions/botName.csproj
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/webapp/botName.csproj
- experimental/generator-adaptive-bot/package.json
As part of the build process for applications generated from the yeoman generator, we need to ensure that all declarative assets are copied to the build output location so that they can be discovered by the runtime host application.
- Update the .csrpoj files for both the web app and Functions templates to include all declarative files (.dialog, .lg, .lu, .qna) in the build output directory at their relative locations, ignoring files from the intermediary output (obj/) and output (bin/) directories.
Manually tested.
> Declarative file includes in yeoman generator templates

- experimental/generator-adaptive-bot/generators/app/index.js
- experimental/generator-adaptive-bot/package.json
Fix template path declaration that has unneeded '\*\*' path declaration. Yeomen does not need '\*\*' to indicate that all contents of the directory need to be copied, instead it looks for a directory called '\*\*' leading to errors.
- removed unneeded path symbols
- updated package version to prep for publish
Manually tested fix in Composer and validated that removal of '**' leads to successful generator instantiation
> Upgrading package name and removing path '**' bug

- experimental/generator-adaptive-bot/generators/app/index.js
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/functions/botName.csproj
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/webapp/botName.csproj
- experimental/generator-adaptive-bot/package-lock.json
- experimental/generator-adaptive-bot/package.json
Our custom template generators will have the need to include additional package references on top of the base references added by generator-adaptive-bot. However, we do not want to add the ability to add package references to the adaptive-bot generator via CLI as it is complex.
This change enables other generators which use generator-adaptive-bot as a sub-generator to optionally supply additional package references which will be included in the generated .csproj, without exposing it as a CLI parameter.
- Read and store packageReferences on generator instance from opts parameter supplied to generator constructor.
- Add templating token for packageReferences to both .csproj files for web app and Functions.
- Include formatted package reference string in generation of .csproj files.
- …
> Generator support for custom package references

- experimental/generator-adaptive-bot/generators/app/templates/assets/appsettings.json
- experimental/generator-adaptive-bot/package.json
The presence of defaultRootDialog in appsettings.json causes the computed root dialog value (first .dialog file in the project directory root) to be overwritten with an empty string, causing the runtime to be unable to load the root dialog.
- Removing 'defautlRootDialog' property from appsettings.json in the generator.
N/A
> Remove defaultRootDialog from generator appsettings.json

- skills/csharp/experimental/newsskill/Deployment/Resources/template.json
- skills/csharp/experimental/newsskill/Dialogs/FavoriteTopicsDialog.cs
- skills/csharp/experimental/newsskill/Dialogs/FindArticlesDialog.cs
- skills/csharp/experimental/newsskill/Dialogs/TrendingArticlesDialog.cs
- skills/csharp/experimental/newsskill/Services/BotSettings.cs
- skills/csharp/experimental/newsskill/Services/NewsClient.cs
This is to fix issues with our experimental C# news skills to account for the migration of the news API from Azure Cognitive Service to Bing Service. 
It also fixes issue with resource provisioning which misses the Azure Maps and the Bing API provision.
Lastly it makes sure the news clients are properly disposing the httpclient underneath.
We added a DelegatingHandler to intercept the HttpRequest and re-write the URL on the fly to account for the fact that the new Bing Service API URI does not have /bing in its relative path.
Tested manually using Azure Bot Service + Bot Emulator. Issue appears unblocked.
None, but we should probably fix documentations.
> Provision correct resources + allow endpoint override

- experimental/generator-adaptive-bot/generators/app/index.js
- experimental/generator-adaptive-bot/generators/app/templates/assets/NuGet.config
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/functions/Startup.cs
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/functions/botName.csproj
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/webapp/Program.cs
- experimental/generator-adaptive-bot/generators/app/templates/dotnet/webapp/botName.csproj
- experimental/generator-adaptive-bot/package-lock.json
- experimental/generator-adaptive-bot/package.json
Following validation of the runtime generator integration in Composer, making a few adjustments to ensure we can fully build, run and publish end-to-end out of the box.
- Enable specifying of the appsettings.json directory to be used by invoking generators through the 'applicationSettingsDirectory' option.
- Enable exclusion of the default appsettings.json file through the 'includeApplicationSettings' option.
- Include NuGet.config as part of app generation with addition of Bot Framework SDK daily package source.
- Update to .csproj files to include .blu files in build output to support Orchestrator recognizer.
Manual validation required following update to Microsoft.Bot.Builder.Runtime package once it is available from daily builds.
> feat: Runtime Generator integration updates

- skills/declarative/todoskill/dialogs/AddToDo/AddToDo.dialog
- skills/declarative/todoskill/dialogs/AddToListOutlook/AddToListOutlook.dialog
- skills/declarative/todoskill/dialogs/CorrectPage/CorrectPage.dialog
- skills/declarative/todoskill/dialogs/DeleteInListOutlook/DeleteInListOutlook.dialog
- skills/declarative/todoskill/dialogs/DeleteToDo/DeleteToDo.dialog
- skills/declarative/todoskill/dialogs/GetToDos/GetToDos.dialog
- skills/declarative/todoskill/dialogs/MarkInListOutlook/MarkInListOutlook.dialog
- skills/declarative/todoskill/dialogs/MarkToDo/MarkToDo.dialog
- skills/declarative/todoskill/dialogs/OAuth/OAuth.dialog
- skills/declarative/todoskill/dialogs/OutlookGetOrCreateTaskFolderAsync/OutlookGetOrCreateTaskFolderAsync.dialog
- skills/declarative/todoskill/dialogs/OutlookGetTaskFoldersAsync/OutlookGetTaskFoldersAsync.dialog
- skills/declarative/todoskill/dialogs/PostAsync/PostAsync.dialog
- skills/declarative/todoskill/dialogs/ShowNextPrev/ShowNextPrev.dialog
Wrong id format in old bots could lead to unhappy experience in Composer.
Refs: https://github.com/microsoft/BotFramework-Composer/issues/5421
`-` -> `_`
> fix: wrong id format in 'todoskill' bot

- build/yaml/pipelines/calendar.yml
- build/yaml/pipelines/generator-adaptive-bot.yml
- build/yaml/pipelines/generator-conversational-core.yml
- build/yaml/pipelines/generator-empty-bot.yml
- build/yaml/pipelines/helpandcancel.yml
- build/yaml/pipelines/msgraph.yml
- build/yaml/pipelines/starter-pipeline.yml
- build/yaml/pipelines/welcome.yml
#480 
All builds are running on any PR, this will explicitly only run buils scoped down to component paths in PRs against the main branch
- Add PR trigger for all pipelines
- Add generator-empty-bot pipeline
- Remove CI rule on updating `preview/*` branches
> DevOps: Stop triggering all builds on any PR

- docs/qnaTemplateReadMe.md
- generators/generator-conversational-core/README.md
- generators/generator-conversational-core/package.json
- generators/generator-empty-bot/README.md
- generators/generator-empty-bot/package.json
This PR updates the read me for the three templates that will be shipped in R12 (Conversational core, empty bot and qna template). 
These new read mes are in a more favorable format for rendering within Composer's 'select template' view
> updating read me for templates to more favorable format for Composer

- build/yaml/pipelines/recognizers-orchestrator.yml
- packages/Microsoft.Bot.Components.sln
- packages/Recognizers.Orchestrator/BotPlugin.cs
- packages/Recognizers.Orchestrator/Microsoft.Bot.Components.Recognizers.Orchestrator.csproj
Adding the Orchestrator recognizer plugin to the official components solution as part of completing #492.
- Add Microsoft.Bot.Components.Recognizers.Orchestrator project to packages/Microsoft.Bot.Components solution.
- Add build pipeline yaml files for Orchestrator pacakge.
Manually verified through integration testing in Composer.
> feat: Add Orchestrator Recognizer plugin component

- generators/generator-microsoft-bot-adaptive/generators/app/index.js
- generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/runtime.json
- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/functions/Startup.cs
- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/Program.cs
- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj
Merging in latest changes to generator-adaptive-bot to support plugins.
- Adding support for pluginDefinitions to generator options to enable other generators to add one or more plugins out of the box when scaffolding the bot.
- Due to package publishing constraints being enforced for security, removing multiple package sources from template NuGet.config.
Manually verified with Composer integration and validation.
> feat: generator-microsoft-bot-adaptive plugin support

- .github/workflows/build-and-test.yml
Had to temporarily disable Calendar tests to unblock check-in of updates to component packages. Re-enabling.
Re-enabling Calendar unit tests.
Automated test coverage.
> bug: Re-enable Calendar tests

- generators/generator-preview-calendar-skill/generators/app/index.js
Need to update to latest package version for Calendar component.
- Update Microsoft.Bot.Components.Calendar package version to 1.0.0-preview1 in generator-preview-calendar-skill.
I like to live dangerously.
> bug: Fix Microsoft.Bot.Components.Calendar version in calendar generator

- generators/generator-microsoft-bot-adaptive/generators/app/index.js
- generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/schemas/readme.md
- generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/schemas/sdk.schema
- generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/schemas/sdk.uischema
- generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/schemas/update-schema.ps1
- generators/generator-microsoft-bot-adaptive/generators/app/templates/assets/schemas/update-schema.sh
- generators/generator-microsoft-bot-adaptive/package-lock.json
Adding the schemas directory and its contents to @microsoft/generator-microsoft-bot-adaptive to assets to ensure it is always written as part of the base generator. Also fixing _writeApplicationSettings to output the correct object.
- Add schemas/**.* to assets output as part of scaffolding.
- Fix _writeApplicationSettings.
> feat: Add schemas to generator-microsoft-bot-adaptive

- generators/generator-microsoft-bot-adaptive/generators/app/index.js
- generators/generator-microsoft-bot-adaptive/package-lock.json
- generators/generator-microsoft-bot-adaptive/package.json
We need to make sure we do not clobber other configured package sources for restoring packages. Due to security enforcements, the NuGet.config was updated to limit to a single source - we need to adjust this for the actual generated project itself and separate from our own build pipeline requirements.
- Update handling of outputting NuGet.config to clear out 'clear' element from packageSources during scaffolding.
Manually tested.
> feat: Remove clear element from scaffolded NuGet.config

- generators/generator-microsoft-bot-adaptive/generators/app/index.js
Async code must be managed appropriately. Noticed this while working on the JS Adaptive Bot generator. See [docs](https://yeoman.io/authoring/running-context.html#asynchronous-tasks) for notes.
> fix: use this.async()

- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/functions/Startup.cs
- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/Startup.cs
Deleting code that was there to compensate for a bug in the SDK. The bug has been fixed, so we don't need that ugly workaround anymore. Yay, less code!
> Adaptive generator: cleanup workaround from startup.cs

- generators/generator-microsoft-bot-command-list/generators/app/templates/settings/appsettings.json
- generators/generator-microsoft-bot-conversational-core/generators/app/templates/settings/appsettings.json
- generators/generator-microsoft-bot-empty/generators/app/templates/settings/appsettings.json
Updating luis:environment setting value to 'composer' for command-list, conversational-core, and empty generators.
- Updating luis:environment setting value to 'composer' for command-list, conversational-core, and empty generators.
N/A
> bug: Update luis:environment setting value to 'composer'

- build/yaml/pipelines/calendar.yml
- build/yaml/pipelines/generator-microsoft-bot-adaptive.yml
- build/yaml/pipelines/generator-microsoft-bot-calendar-assistant.yml
- build/yaml/pipelines/generator-microsoft-bot-calendar.yml
- build/yaml/pipelines/generator-microsoft-bot-command-list.yml
- build/yaml/pipelines/generator-microsoft-bot-conversational-core.yml
- build/yaml/pipelines/generator-microsoft-bot-empty.yml
- build/yaml/pipelines/graph.yml
- build/yaml/pipelines/helpandcancel.yml
- build/yaml/pipelines/onboarding.yml
- build/yaml/pipelines/orchestrator.yml
- build/yaml/pipelines/starter-pipeline.yml
- build/yaml/pipelines/welcome.yml
- build/yaml/templates/nuget-signing-steps.yml
Update pipelines to work on the SDK_V4 ADO team
- Pipeline names are simply BuildId value so they are easier to parse
- CI & PR triggers wil be configured in Pipelines, so they can share the same YAML templates as the Daily builds
- Use the same signing service connection as SDK
> Pipelines: Migration to SDK_V4 ADO team

- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj
Fixes https://github.com/microsoft/botframework-components/issues/675.
Updating .csproj templates in @microsoft/generator-microsoft-bot-adaptive to include .onnx and .txt files in build output to support Orchestrator.
- Updating .csproj templates in @microsoft/generator-microsoft-bot-adaptive to include .onnx and .txt files in build output to support Orchestrator.
> feat: Include .onnx and .txt content in build output

- generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/Startup.cs
- generators/generator-microsoft-bot-conversational-core/generators/app/index.js
- generators/generator-microsoft-bot-conversational-core/generators/app/templates/conversational-core.dialog
- generators/generator-microsoft-bot-conversational-core/generators/app/templates/language-generation/en-us/conversational-core.en-us.lg
- generators/generator-microsoft-bot-conversational-core/generators/app/templates/language-understanding/en-us/conversational-core.en-us.lu
Fixes #683 
* Added missing using for Microsoft.Extensions.Hosting in adaptive startup.cs
* Tuned up the LUIS model for convcore by removing some utterances and adding some utterances to the none
* Updated convcore references to use the latest welcome and help and cancel packages and wired up the dialogs to the root dialog
* Removed extra #designer element in conversational-core.dialog
* Removed reference to SDK schema from conversational-core.dialog (this is not needed)
* Added condition to the cancel intent to only trigger on 90% certainty. 
* Updated SendActivity calls to use the Response Editor format
**Note:** the luis model has too few utterances and it has no real end user intents, we should let the devs know if the documentation about the need to tune the LUIS model and make sure …
> Fixes cancel intent and other conversational-core updates

- generators/generator-bot-assistant-core/generators/app/templates/assistantCore.dialog
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/assistantCore.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/common.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/recognizers/assistantCore.en-us.lu.dialog
- generators/generator-bot-assistant-core/generators/app/templates/recognizers/assistantCore.lu.dialog
- generators/generator-bot-assistant-core/generators/app/templates/recognizers/assistantCore.lu.qna.dialog
Adding stubs for disambiguation, error handling, and unknown intent handling to the Assistant Core generator.
- Added `Microsoft.OnChooseIntent` trigger and prepackaged dialog for disambiguation #737. Orchestrator will test against as they work on their related bugs.
- Added `Microsoft.OnError` trigger sending a friendly response back to user and trace event per #689, will keep this in sync with Conversation Core template. The runtime should handle logging to a logging provider per the [OnTurnError in CoreBotAdapter](https://github.com/microsoft/botbuilder-dotnet/blob/514abdf64602f333c62033a67904d2e026458d5a/libraries/integration/Microsoft.Bot.Builder.Integration.Runtime/CoreBotAdapter.cs#L53), but this needs further validation when there is a component in this template that can error. I …
> feat: Add OnAmbiguousIntent, OnError, and OnUnknownIntent to Assistant Core

- generators/generator-bot-assistant-core/generators/app/index.js
- generators/generator-bot-calendar-assistant/generators/app/index.js
- generators/generator-bot-calendar/generators/app/index.js
- generators/generator-bot-command-list/generators/app/index.js
- generators/generator-bot-conversational-core/generators/app/index.js
- generators/generator-bot-empty/generators/app/index.js
- generators/generator-bot-enterprise-assistant/generators/app/index.js
- generators/generator-bot-people/generators/app/index.js
- generators/generator-bot-qna-maker/generators/app/index.js
Turns out, if you update package names, you also need to update references to those packages to use the new names. Who knew?!
- Fixing generator package references to utilize new names.
> Fixing references to @microsoft/generator-bot-adaptive.

- packages/Graph/Microsoft.Bot.Components.Graph.csproj
Nuget pack duplicates the schema files by default which breaks dialog:merge
I took the pattern used by the Bot Builder Community package to resolve this issue. Worked when testing the muget package locally
> Update Graph project config

- generators/generator-bot-adaptive/generators/app/index.js
- generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
- generators/generator-bot-adaptive/generators/app/templates/dotnet/NuGet.config
Fixes #787.
This change addresses a number of small fixes that need to be made for R13.
- NuGet.config removed from template files. This was originally added to support being able to restore packages from MyGet during development. This is no longer needed, and we don't need to expose the MyGet endpoint to consumers.
- Updating the adaptive generator to include dotnet template settings for including the .sln file, with default to true. This is to support the Enterprise Assistant template, which for now will need to override the default behavior so as to avoid generating separate .sln files for each bot.
- Adding 'region' property with default value of 'westus' to qna settings in appsettings.json.
> More Generator fixes

- generators/generator-bot-adaptive/generators/app/index.js
- generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
Invocation to modifyApplicationSettings as part of _writeApplicationSettings within generator-bot-adaptive had been inadvertently dropped. This was impacting child generators which attempted to modify the base appsettings.
- Add invocation of this.modifyApplicationSettings back to _writeApplicationSettings in generator-bot-adaptive.
> Invoke this.modifyApplicationSettings in generator-bot-adaptive

- generators/generator-bot-conversational-core/generators/app/templates/botName.dialog
- generators/generator-bot-conversational-core/generators/app/templates/language-generation/en-us/botName.en-us.lg
Fixes #689
This PR adds an error trigger to the root dialog and sends a friendly message and a trace with exception details to emulator (it is good to show devs where to find the exception details in memory).
It also removes the $schema property that was erroneously added to botName.dialog and removes a duplicated element from that dialog.
> Adds error handler to conversational core

- generators/generator-bot-assistant-core/generators/app/templates/botName.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/language-generation/en-us/BotTourDialog.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/recognizers/BotTourDialog.en-us.lu.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/recognizers/BotTourDialog.lu.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/recognizers/BotTourDialog.lu.qna.dialog
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/botName.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/common.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/language-understanding/en-us/botName.en-us.lu
#468 Bot Tour
#500 Assistant Core items
The **Greeting** component greets both new and returning users in a HeroCard with actionable buttons (rather than suggested actions so it is Teams-compatible). The user can select "You can ask me" to trigger the Bot Tour (or say things like "get started").
The Bot Tour component starts with a collapsible Adaptive card (thanks PbX) filled with dummy content. 
If a user selects one of the items it opens to a more detailed focus card. All of the Bot Tour content will be replaced with demo content at a later point.
Exported …
> Assistant Core: Implement Welcome and Bot Tour features

- generators/generator-bot-assistant-core/generators/app/templates/botName.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/FeedbackDialog/language-generation/en-us/FeedbackDialog.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/botName.en-us.lg
#500 Items in Assistant Core template
#737 Enable "Duplicated intents recognized" trigger to enable disambiguation
#738 Update LG for FeedbackDialog
- Disambiguation: The "duplicated intents recognized" trigger is installed via a template factory in Composer, so the dialog is already preconfigured with LG. This is assumed to work out of the box with the SDK and there are follow up items on Orchestrator to ensure it works as expected.
- Feedback: Added variations to responses in FeedbackDialog
> Assistant Core: Add OnChooseIntent and FeedbackDialog updates

- packages/Graph/Microsoft.Bot.Components.Graph.csproj
- packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec
- packages/Onboarding/Microsoft.Bot.Components.Onboarding.nuspec
- packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec
README.md with post-installation instructions needs to be included in all generator and component packages. The .NET component packages did not include it in their content. This change adds it to applicable packages.
- Update Graph, HelpAndCancel, Onboarding and Welcome component packages to include README.md as part of content in .NET NuGet packages.
> fix: Adding README.md to included content in component packages

- generators/generator-bot-adaptive/generators/app/index.js
- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
.NET Functions did not successfully compile out of the box when a bot was scaffolded on that integration and platform. This change ensures it runs successfully when scaffolded.
- Updated .NET Functions .csproj to have correct includes for appsettings.json.
- Updated Adaptive generator to supply appsettings include path as a template parameter to generated .csproj.
Manually verified with both the Adaptive and Empty generators.
> fix: .NET Functions .csproj fixes

- generators/generator-bot-adaptive/generators/app/index.js
If the adaptive generator is run via CLI directly, it throws due to unhandled exception where this.applicationSettingsDirectory is undefined. This change handles this cleanly.
- Update _copyPlatformTemplate to handle if this.applicationSettingsDirectory is not set and default to empty string.
> fix: settingsIncludePath in @microsoft/generator-bot-adaptive handles undefined

- generators/generator-bot-adaptive/package.json
- yarn.lock
Use the `~` operator to limit to `5.1.x` runtypes versions.
> fix: runtypes version resolution

- packages/Graph/Actions/BaseMsGraphCustomAction.cs
- packages/Graph/Actions/User/GetDirectReports.cs
- packages/Graph/Actions/User/GetManager.cs
- packages/Graph/Actions/User/GetPeers.cs
- packages/Graph/Actions/User/GetUserProfile.cs
- packages/Graph/Actions/User/GetUsers.cs
- packages/Graph/Schemas/Microsoft.Graph.User.GetDirectReports.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetManager.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetPeers.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetUserProfile.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetUsers.schema
- skills/declarative/tests/whoSkill/WhoSkillTestBase.cs
- skills/declarative/whoSkill/whoSkill.sln
- skills/declarative/whoSkill/whoSkill/Controllers/BotController.cs
- skills/declarative/whoSkill/whoSkill/Controllers/SkillController.cs
- skills/declarative/whoSkill/whoSkill/Program.cs
- skills/declarative/whoSkill/whoSkill/Startup.cs
- skills/declarative/whoSkill/whoSkill/dialogs/WhoIsDirectReportDialog/WhoIsDirectReportDialog.dialog
- skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/WhoIsManagerDialog.dialog
- skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPeerDialog/WhoIsPeerDialog.dialog
- skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/WhoIsPersonDialog.dialog
- skills/declarative/whoSkill/whoSkill/dialogs/WhoWorksWithMeDialog/WhoWorksWithMeDialog.dialog
- skills/declarative/whoSkill/whoSkill/schemas/sdk.schema
Limit the amount of data being retrieved in the People Skill-related Graph calls. This serves two purposes:
1. Limit the size of the payload we have to transfer across the wire
2. Limit unnecessary PII data exposure on behalf of end user
This change also updates the People skill to use the RC2 style bot app initialization.
Switch to using explicit SELECT() clause in the Graph API to return only relevant information.
Existing unit tests
Ideally the "select()" statement's list of columns are configurable. I think there could be some more thoughts put into it, like we can probably ask the bot custom action to add a parameter for "fields" …
> Limit Graph Object Fields using Select() in People Skill

- packages/AdaptiveCards/Microsoft.Bot.Components.AdaptiveCards.csproj
- packages/Directory.Build.props
- packages/Graph/Microsoft.Bot.Components.Graph.csproj
- packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec
- packages/HelpAndCancel/package.json
- packages/Teams/Microsoft.Bot.Components.Teams.csproj
- packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec
- packages/Welcome/package.json
Close #880
There are a couple of items in the directory.build.props that are included in packaging that are better served being in the project files themselves. The RepositoryUrl should point to each package's own README as that is what is linked under "View Documentation" in Composer, while the PackageTags should be provided in project files themselves (build properties takes precedence over project properties).
Added "homepage" property to package.json files that point to the package READMEs.
The Teams README is missing, this is requested in #877.
> fix: consolidate package properties

- generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
- generators/generator-bot-template-generator/app/templates/generators/app/templates/settings/appsettings.json
Fixes #892.
Due to https://github.com/microsoft/botbuilder-dotnet/issues/5479, defaultLocale must be changed to 'en-us' in order to ensure it matches the casing specified in the recognizer files, otherwise it is unable to select the correct recognizer for incoming requests.
- Updating defaultLocale value in appsettings.json to 'en-us'.
Manual verification.
> fix: Updating defaultLocale value in appsettings.json to 'en-us'

- skills/declarative/Calendar/Calendar/.gitignore
- skills/declarative/Calendar/Calendar/settings/appsettings.json
- skills/declarative/whoSkill/whoSkill/.gitignore
- skills/declarative/whoSkill/whoSkill/settings/appsettings.json
The default app settings in our project currently do not start properly under composer for adaptive runtime as it is not configured properly to hint and thus falling into the old custom azurewebapps runtime.
This change is to make the adaptive runtime setting stick in the appsettings.
- Update gitignore to not ignore appsettings
- Update appsettings to use adaptive runtime for runtime setting
Manually tested
None
> Make appsettings for Pbx projects stick for adaptive runtime

- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
- generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj
Currently the runtime has a set of built-in components that cannot be removed and are statically registered. Many of these make sense even in the super long term such as AdaptiveDialogs or BotBuilder. However, other of the core components that we've always registered are Luis and QnA. With the new component model, in R14 we would want to remove Luis and QnA and have them be only registered as components by the generators that need them. This will decouple the runtime from LUIS + QnA and also allow users to not have dependencies they won't want.
This change prepares the terrain for that to reduce breaking changes and need for migrations in R13 generators when upgrading to r14.
> Adaptive generator: add reference to luis + qna for r14 legacy story

- generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
After confirming with the Composer team, downsampling settings are deprecated. Removing from scaffolded appsettings.json.
- Removing downsampling settings from appsettings.json in Adaptive generator templates.
N/A
> fix: Remove downsampling settings

- skills/declarative/Calendar/Calendar/dialogs/AuthenticationDialog/AuthenticationDialog.dialog
- skills/declarative/whoSkill/whoSkill/dialogs/AuthenticationDialog/AuthenticationDialog.dialog
Emit a trace entry when the required oAuthConnectionName is not present in the setting or is empty string.
- Updated the authentication dialog in People and Calendar skill to reflect the check
Manually test.
Integrate with template
> Emit trace when the bot does not have oAuthConnectionName configured

- generators/generator-bot-assistant-core/generators/app/templates/botName.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/language-generation/en-us/BotTourDialog.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/ChitchatDialog/ChitchatDialog.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/ChitchatDialog/language-generation/en-us/ChitchatDialog.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/FeedbackDialog/FeedbackDialog.dialog
- generators/generator-bot-assistant-core/generators/app/templates/dialogs/FeedbackDialog/language-generation/en-us/FeedbackDialog.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/botName.en-us.lg
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/common.en-us.lg
- generators/generator-bot-conversational-core/generators/app/templates/botName.dialog
- generators/generator-bot-conversational-core/generators/app/templates/language-generation/en-us/botName.en-us.lg
- generators/generator-bot-empty/generators/app/templates/botName.dialog
- generators/generator-bot-empty/generators/app/templates/language-generation/en-us/botName.en-us.lg
- generators/generator-bot-empty/generators/app/templates/language-generation/en-us/common.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/BotTourDialog/language-generation/en-us/BotTourDialog.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/ChitchatDialog/ChitchatDialog.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/ChitchatDialog/language-generation/en-us/ChitchatDialog.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/FeedbackDialog/FeedbackDialog.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/FeedbackDialog/language-generation/en-us/FeedbackDialog.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/language-generation/en-us/botName.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/language-generation/en-us/common.en-us.lg
- packages/HelpAndCancel/exported/CancelDialog/CancelDialog.dialog
- packages/HelpAndCancel/exported/CancelDialog/language-generation/en-us/CancelDialog.en-us.lg
- packages/HelpAndCancel/exported/HelpDialog/HelpDialog.dialog
- packages/HelpAndCancel/exported/HelpDialog/language-generation/en-us/HelpDialog.en-us.lg
- packages/Welcome/exported/WelcomeDialog/WelcomeDialog.dialog
- packages/Welcome/exported/WelcomeDialog/language-generation/en-us/WelcomeDialog.en-us.lg
Close #895 
Close #938 
This pull request refactors the LG templates to adhere to Composer's schema (so that they may render as expected in the UI) while having a friendly name for users inspecting through the Bot Responses tab. With the intention of aligning to Composer standards, the template format I've opted for is:
```
SendActivity_{description}_{property}_{id}
```
- Description gives context to what the bot's response is
- Property is the activity property (text, speak, attachments), this is what Composer looks for
- Id is the final id should properties need to identify uniquely, like attachments
*Are there any changes that need to be called out as significant or particularly difficult to grasp? (Include illustrative …
> refactor: simplify LG template usage across templates and packages

- generators/generator-bot-assistant-core/generators/app/templates/botName.dialog
- generators/generator-bot-assistant-core/generators/app/templates/language-generation/en-us/botName.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/language-generation/en-us/botName.en-us.lg
Close #954 which updates the disambiguation feature for the Core and Enterprise Assistant templates. The LG templates are renamed in the same manner as #955. See microsoft/botframework-composer#7004 for additional context.
> fix: Core/Enterprise Assistant replace ChooseIntent implementation

- packages/Graph/Schemas/Microsoft.Graph.Calendar.AcceptEvent.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.CreateEvent.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.DeclineEvent.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.DeleteEvent.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.FindMeetingTimes.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.GetContacts.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.GetEventById.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.GetEvents.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.GetWorkingHours.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FindAvailableTimes.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.GroupEventsByDate.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.RecognizeDateTime.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.TentativelyAcceptEvent.schema
- packages/Graph/Schemas/Microsoft.Graph.Calendar.UpdateEvent.schema
- packages/Graph/Schemas/Microsoft.Graph.Photo.GetPhoto.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetDirectReports.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetManager.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetPeers.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetProfile.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetUserProfile.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetUsers.schema
- packages/Graph/Schemas/Microsoft.Graph.User.GetWorksWith.schema
A lot of the example in the Graph package schemas are rather meaningless. Potentially leading to confusion in people who consumes these templates.
Update the examples in the schema to include better ones:
- The examples are now more realistic, instead of "Hello ${user.name}" it would not say things like "turn.result" something that makes sense to the specific scenario
- If the property is an _input_ driven from something in the memory scope, then they would include "=" at the start to denote to give people better idea that is an adaptive expression to resolve a value from the memory scope.
Tested by updating schema in the Composer than ensuring the samples are showing up.
Update the Graph package with the improved schema examples
> Add better examples for Graph package schemas

- generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/BotTourDialog/language-generation/en-us/BotTourDialog.en-us.lg
- generators/generator-bot-enterprise-assistant/generators/app/templates/language-generation/en-us/botName.en-us.lg
If the root bot does not have allowedCallers configured and throws an error, the bot will send a message to explain.
This will only be shown in the emulator channel.
Fixes: #973
> [EA] Added allowed callers error message

- build/yaml/pipelines/calendar.yml
- build/yaml/pipelines/people.yml
Add CICD pipelines for calendar people skill that was originally GH actions but now has to move to ADO.
New pipeline definitions to build the bot csproj and then run tests
> New pipelines for calendar and people

- .github/auto_assign.yml
We have the [auto-assign](https://github.com/kentaro-m/auto-assign/) bot installed but not enabled on this repository and would benefit from automating more of our process. 
- When the pull request is opened, automatically add reviewers/assignees to the pull request.
- If the number of reviewers is specified, randomly add reviewers/assignees to the pull request.
- If reviewers/assignees are separated into groups in the config file, randomly select the number of reviewers from each group.
- If the title of the pull request contains a specific keyword, do not add reviewers/assignees to the pull request.
Close #979, which enables the auto-assign bot to add a PR author as the designated assignee. This also cleans up the …
> maintenance: Enable auto-assign pull request author to assignee

- .github/workflows/pr-labeler.yml
Remove extraneous `"` in PR labeler action
#minor
> chore: fix typo in pr-labeler action

- generators/generator-bot-core-assistant/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog
- generators/generator-bot-core-assistant/generators/app/templates/dialogs/BotTourDialog/language-generation/en-us/BotTourDialog.en-us.lg
Close #1032 
#1023 introduced additional edge cases where interruptions didn't work as expected, this addresses that by reverting to the better understood intent routing logic used before.
DetailsCard sends an activity with a card attachment.
Each suggested action maps to its own intent and response that can be customized by the user.
> fix: replace Basic Assistant bot tour multichoice logic with intents

- build/yaml/templates/npm-versioning-steps.yml
When attempting to run the Teams JS daily build, it fails due to NpmPackageVersion not being set in npm-versioning-steps.yml. This is because it only gets set when the component type is 'declarativeAsset' or 'generator', and in this case it needs to also run when component type is 'codeExtension' and language is 'js'.
Given that we only enter into this step when those conditions are true, due to the same check being applied at stage_package_node in component-template.yml, and we should always have a package.json for these cases, the additional condition is redundant, so removing it altogether.
- Removing redundant componentType check in npm-versioning-steps.yml.
Manually running daily pipeline against this branch. Will verify before merging.
#minor
> fix: Removing redundant componentType check in npm-versioning-steps.yml.

- build/yaml/templates/npm-build-steps.yml
Run build script if defined in `package.json`
Some packages may define a `build` script that should be executed as part of the publish. This ensures the script is executed.
#minor
> fix: run build script if present

- build/yaml/templates/component-template.yml
- packages/Teams/js/package.json
- yarn.lock
Running `downlevel` broke CI for whatever reason - it's not necessary, though, as we aren't targeting old Typescript versions.
#minor
> fix: remove downlevel support

- docs/assets/MultiplyDialog.cs
- docs/assets/MultiplyDialog.csproj
- docs/assets/MultiplyDialog.schema
- docs/assets/MultiplyDialogBotComponent.cs
- docs/extending-with-code.md
> docs: Udpated extending-with-code doc

- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
Fixes #1063.
- Updating .NET Functions .csproj template to include all *.json files (except in www directory) as content.
- `local.settings.json` continues to not excluded in publish output.
- Fix www item include to use POSIX-style path separators.
- Add `_FunctionsSkipCleanOutput` to PropertyGroup with value set to `true`.
Testing still required - WIP.
> fix: .NET Functions .csproj template fixes

- build/yaml/templates/component-template.yml
- build/yaml/templates/dotnet-build-test-steps.yml
- build/yaml/templates/dotnet-install-sdk-steps.yml
- packages/Microsoft.Bot.Components.sln
Running the .NET: Version, Sign & Pack stage (job: job_pack_dotnet) is currently failing in Daily builds against main. This appears to be caused by build properties picked up from .NET 5 SDK which are clobbering ours defined in packages/Directory.Build.props.
This error is not occurring during the .NET: Build & Test stage, where the dotnet CLI Version being used is 3.1.x.
- Update the .NET: Version, Sign & Pack stage to explicitly install .NET Core 2.1.x and 3.1.x SDKs for the job_pack_dotnet job to match behavior in .NET: Build & Test stage and not default to .NET 5.
- Removing reference to non-existent .editorconfig file in Microsoft.Bot.Components.sln.
Running daily pipelines manually against branch to verify.
#minor
> fix: Install .NET Core SDK for '.NET: Version, Sign & Pack' CI/CD pipeline stage

- generators/generator-bot-core-assistant/generators/app/templates/botName.dialog
- generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog
Per Switch [schema](https://github.com/microsoft/botbuilder-dotnet/blob/402bc02b4cbbd2f4ec359134640e99211367e4a5/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Actions/Microsoft.SwitchCondition.schema#L17), this conditional is expecting a `StringExpression`,  and I was feeding it an integer. 
Strangely, Composer did not show a validation error on this bug until recently.  Thanks @tdurnford  and @hatpick  for explaining the validation logic in Composer.
With this fix, template doesn't throw anymore errors and bot can be built.
fixes microsoft/botframework-composer#7700 
adding #minor for validation because the linked issue is in another repo
> fix: convert switch case condition to stringexpression, per schema definition

- tests/Microsoft.Bot.Components.Tests.sln
Fixes the solution file to point to the updated version of the Teams package for dotnet. This isn't really needed for R13.
- Update .sln file to point to /dotnet directory of Teams package
Yes, ran dotnet test locally with the .sln
> fix: Test sln point to new dotnet path for Teams package

- generators/generator-bot-adaptive/generators/app/index.js
- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/Triggers/StaticFilesTrigger.cs
- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
Fixes #1112.
- Update .NET Functions template files in @microsoft/generator-bot-adaptive to use wwwroot as the directory to serve static files from.
- Update JS SDK dependency version to 4.13.3-preview.
N/A
> fix: Update .NET Functions to use wwwroot dir for static files

- generators/generator-bot-adaptive/generators/app/templates/js/webapp/web.config
Fixes #7776  (In Composer repo)
This configures the iisnode to send requests for the manifests file to the webapp, which can then serve them through the wwwroot/manifests folder.
OTHERWISE, iisnode sees the root /manifests folder and gets confused, resulting in an internal server error and a 404 to the client.
* Add rewrite rule for manifests for web.config file
> fix: add rewrite rule for manifest files for js webapps

- packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj
- packages/Teams/dotnet/README.md
Update Teams package tags
#minor
> chore: Add tags to Teams component project file

- .gitignore
- packages/Telephony/Actions/CallTransfer.cs
- packages/Telephony/Actions/PauseRecording.cs
- packages/Telephony/Actions/ResumeRecording.cs
- packages/Telephony/Actions/StartRecording.cs
- packages/Telephony/Common/CommandDialog{T}.cs
- packages/Telephony/Common/RecordingStartSettings.cs
- packages/Telephony/Common/TelephonyExtensions.cs
- tests/Microsoft.Bot.Components.Tests.sln
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/Recording_BaseScenario.test.dialog
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/StartRecording_CommandResultWrongName.test.dialog
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/StartRecording_HappyPath.test.dialog
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/StartRecording_IgnoredInNonTelephonyChannel.test.dialog
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/StartRecording_WithTangent_InterruptionDisabled.test.dialog
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/StartRecording_WithTangent_InterruptionEnabled.test.dialog
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/IntegrationTestsBase.cs
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/Microsoft.Bot.Components.Telephony.Tests.csproj
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/NuGet.Config
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/RecordingTests.cs
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/ResourceExplorerFixture.cs
- tests/packages/Microsoft.Bot.Components.Telephony.Tests/TestUtils.cs
> chore: [Internal dev branch PR] Telephony: integration tests and CommandDialog interruption model first pass

- generators/generator-bot-adaptive/baseGenerator.js
- generators/generator-bot-adaptive/generators/app/index.js
- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
- generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj
- generators/generator-bot-adaptive/platforms.js
Fixes #1136 
This does NOT address the floating sdk dependencies.
> feat: generator-bot-adaptive: Added command line option to specify SDK version

- build/yaml/templates/component-template.yml
- build/yaml/templates/npm-test-steps.yml
- generators/generator-bot-adaptive/generators/app/index.js
Wiring up generator-bot-adaptive unit tests as part of CI/CD pipeline.
- Wiring up generator-bot-adaptive unit tests as part of CI/CD pipeline.
Exercising existing unit tests for generator-bot-adaptive.
#minor
> chore: Wire up yeoman unit tests in CI/CD pipelines

- generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetManagerDialog/GetManagerDialog.dialog
- generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetManagerDialog/GetManagerDialog.dialog.schema
- skills/declarative/People/People/dialogs/GetManagerDialog/GetManagerDialog.dialog
- skills/declarative/People/People/dialogs/GetManagerDialog/GetManagerDialog.dialog.schema
Fixing the get manager intent issue where the name entity is not set for the dialog invocation of ResolveUserDialog. Closes #1108.
Update both People project and template.
Manually tested the scenario in Emulator.
none, release this bug fix as part of R14.
> fix: GetManager issue with name entity not set

- packages/Teams/dotnet/Actions/SendMessageToTeamsChannel.cs
Fixes: https://github.com/microsoft/botframework-components/issues/1169
Enable SendMessageToTeamsChannelAsync with CloudAdapter changes
> fix: Update SendMessageToTeamsChannelAsync to work with CloudAdapter

- packages/Teams/dotnet/Actions/SendMessageToTeamsChannel.cs
fixes: https://github.com/microsoft/botframework-components/issues/1169
> fix: Send message to teams channel support both adapters

- generators/generator-bot-adaptive/platforms.js
- generators/generator-bot-adaptive/test/js-functions.test.js
- generators/generator-bot-adaptive/test/js-webapp.test.js
- generators/generator-bot-core-assistant/generators/app/index.js
- generators/generator-bot-core-language/generators/app/index.js
- generators/generator-bot-enterprise-calendar/generators/app/index.js
- generators/generator-bot-enterprise-people/generators/app/index.js
- packages/AdaptiveCards/Microsoft.Bot.Components.AdaptiveCards.csproj
- packages/Graph/Microsoft.Bot.Components.Graph.csproj
- packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec
- packages/HelpAndCancel/package.json
- packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj
- packages/Teams/js/package.json
- packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec
- packages/Welcome/package.json
Bump package versions for Teams, Graph, Welcome, AdaptiveCard and Cancel.
Bump package versions for Teams, Graph, Welcome, AdaptiveCard and Cancel to force upgrade of SDK runtime version.
> feat: Update package versions

- tests/functional/build/yaml/deployBotResources/deployBotResources.yml
- tests/functional/build/yaml/deployBotResources/dotnet/deploy.yml
- tests/functional/build/yaml/deployBotResources/dotnet/evaluateDependenciesVariables.yml
- tests/functional/build/yaml/deployBotResources/generator/deploy.yml
- tests/functional/build/yaml/deployBotResources/js/deploy.yml
- tests/functional/build/yaml/deployBotResources/js/evaluateDependenciesVariables.yml
#1069 #minor
This pull request refactors the skills functional tests to create an Empty Bot from the local genreator-bot-empty in javascript, for both web app and functions integrations.
- Updated /deployBotResources.yml
- Pass parameters used with bot project generators: local generator, name, platform, and integration
- Updated /js/deploy
- Remove unused steps copied over from skills tests
- Add steps to deploy a template with the generator
- Add debugging step 
- Remove additional references to SkillV3 bots (unused) in the JS deploy steps
- Rename the working directory to /workspace to better differentiate when viewing debug output
- 
**Pipeline passing for all combinations**
**Web App in Azure greets as expected**
These are test resources.
Follow up with a PR to deploy an Azure …
> feat: functional tests generate empty bots in js

- build/yaml/templates/npm-versioning-steps.yml
Right now only RC gets to name versions RC.0, RC.1, etc. However there is a need for preview package to do it too. Furthermore, there is interdependency in the package such that a dynamically generated version of the package won't work well (because you'd need to check back in the new version number). Need more thoughts but this should help us unblock R14.
> fix: Allow previews to generate suffix version as well

- build/yaml/templates/nuget-versioning-steps.yml
- tests/unit/packages/Microsoft.Bot.Components.Teams.Tests/Microsoft.Bot.Components.Teams.Tests.csproj
- tests/unit/skills/calendar/Microsoft.Bot.Dialogs.Tests.Skills.Calendar.csproj
- tests/unit/skills/common/Microsoft.Bot.Dialogs.Tests.Common.csproj
- tests/unit/skills/people/Microsoft.Bot.Dialogs.Tests.Skills.People.csproj
Allow preview ring to also specify a version override
> fix: nuget package version override to allow "preview" ring

- packages/Directory.Build.props
- packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec
- packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec
- skills/csharp/Directory.Build.props
- tests/functional/Directory.Build.props
- In Directory.Build.props (for .csproj packages), replace deprecated `LicenseUrl` property with `PackageLicenseExpression`.
- In .nuspec files, replace deprecated `licenseUrl` property with `license type='expression'`
- Add NU5048 to NoWarn for PackageIconUrl/iconUrl as we will continue to use it to reference the icon.png on botframework-sdk repo (and fix reference to point to main branch)
#minor
> chore: update deprecated nuget package licenseurl properties

- packages/HelpAndCancel/package.json
- packages/Welcome/package.json
The npm pipelines with declarative assets do not have any tests associated with them, but due to limitations in yarn we are unable to have a pipeline appropriately discern if they are available. 
Some background via comment in the yaml file:
> You are probably wondering "Why not just run 'yarn exec npm run --if-present test'?".
> On Azure Pipelines, yarn install by default restores modules to a global node_modules cache
> instead of a local package cache. When running the npm CLI, it is unable to resolve required
> dependencies as a result, whereas yarn run <script> can do so successfully. However,
> yarn does not yet have an --if-present condition - the immediate step below simulates this
> by manually reading the package.json and checking for the presence of $.scripts.test in the JSON. …
> chore: fix response for missing text scripts in npm packages

- packages/Teams/dotnet/Actions/GetMeetingInfo.cs
- packages/Teams/dotnet/Schemas/Actions/Teams.GetMeetingInfo.schema
- packages/Teams/dotnet/Schemas/Actions/Teams.GetMeetingInfo.uischema
- packages/Teams/dotnet/Schemas/TriggerConditions/Teams.OnMeetingEnd.schema
- packages/Teams/dotnet/Schemas/TriggerConditions/Teams.OnMeetingEnd.uischema
- packages/Teams/dotnet/Schemas/TriggerConditions/Teams.OnMeetingStart.schema
- packages/Teams/dotnet/Schemas/TriggerConditions/Teams.OnMeetingStart.uischema
- packages/Teams/dotnet/TeamsBotComponent.cs
- packages/Teams/dotnet/TriggerConditions/OnTeamsMeetingEnd.cs
- packages/Teams/dotnet/TriggerConditions/OnTeamsMeetingStart.cs
Addresses .NET: #1138 
Addresses .NET: #1139
#minor (have to include since this doesn't fully fix an issue)
Add the action, `GetMeetingInfo()`
Adds the Triggers, `OnTeamsMeetingStart`() and `OnTeamsMeetingEnd()`
I triggered `GetMeetingInfo()` to send on Unknown Intent:
Meeting start/end events (data is on `activity.value`):
This relies on updating to v4.14 of the SDK (which this PR does not do--it's meant to be ready-to-go after that update gets pushed)
I'll start working on the JS versions. Should be ready to review by Wednesday.
> port: GetMeetingInfo, meeting start/end events [.NET]

- packages/Telephony/Readme.md
Add skeleton for mini-spec for Telephony actions
Add skeleton for mini-spec for Telephony actions
This is a doc only change
#minor
> chore:Add mini-spec for Telephony actions

- generators/command-line-instructions.md
- generators/generator-bot-adaptive/README.md
- generators/generator-bot-core-assistant/README.md
- generators/generator-bot-core-language/README.md
- generators/generator-bot-core-qna/README.md
- generators/generator-bot-empty/README.md
- generators/generator-bot-enterprise-assistant/README.md
- generators/generator-bot-enterprise-calendar/README.md
- generators/generator-bot-enterprise-people/README.md
- generators/generator-bot-template-generator/README.md
FIxed broken URLs that cause issues with readmes in Composer
#minor
> fix: Broken links that open url in Composer modal

- packages/Telephony/Readme.md
Complete call recording extensions package mini-spec
Complete call recording extensions package mini-spec
n/a. This is a doc only change
n/a. This is a doc only change
#minor
> chore: Complete call recording extensions package mini-spec

- generators/generator-bot-core-language/generators/app/index.js
- generators/generator-bot-core-qna/package.json
- generators/generator-bot-empty/package.json
- generators/generator-bot-enterprise-assistant/package.json
- generators/generator-bot-enterprise-calendar/generators/app/index.js
- generators/generator-bot-enterprise-calendar/package.json
- generators/generator-bot-enterprise-people/generators/app/index.js
- generators/generator-bot-enterprise-people/package.json
- yarn.lock
Update the Components repository to 1.1.0 GA for immanent release.
#minor
> feat: Update to 1.1.0 GA for Components

- build/templates/template-function-bot-resources.json
- build/templates/template-function-dotnet-bot-resources.json
- build/templates/template-function-js-bot-resources.json
- tests/functional/Tests/ComponentsFunctionalTests/Common/HostBot.cs
- tests/functional/Tests/ComponentsFunctionalTests/EmptyBot/EmptyBotTests.cs
- tests/functional/Tests/ComponentsFunctionalTests/appsettings.json
- tests/functional/build/yaml/deployBotResources/dotnet/deploy.yml
- tests/functional/build/yaml/deployBotResources/js/deploy.yml
- tests/functional/build/yaml/testScenarios/configureConsumers.yml
- tests/functional/build/yaml/testScenarios/runTestScenarios.yml
Close #1069 
Add ARM templates for Functions App deployment, taken from Composer's copy and modified. 
Adds Empty Bot Dotnet/JS Functions App to test cases
This closes out the MVP for #1069, with an Empty Bot deploying in all variations and passing tests over Direct Line.
> build: add functions app deployment/testing to functional tests

- .gitignore
- build/templates/template-function-dotnet-bot-resources.json
- build/templates/template-function-js-bot-resources.json
- tests/functional/Tests/ComponentsFunctionalTests/Common/HostBot.cs
- tests/functional/Tests/ComponentsFunctionalTests/EmptyBot/EmptyBotTests.cs
- tests/functional/Tests/ComponentsFunctionalTests/appsettings.json
- tests/functional/build/yaml/deployBotResources/dotnet/deploy.yml
- tests/functional/build/yaml/deployBotResources/js/deploy.yml
- tests/functional/build/yaml/testScenarios/configureConsumers.yml
- tests/functional/build/yaml/testScenarios/runTestScenarios.yml
Merge main to Telephony to remove new conflicts 
- git merge main --no-ff
- Build Bot.Framework.Components.sln and tests
- Run all unit tests and ensure no failure
#minor
> chore:Merge main to Telephony to remove new conflicts 

- packages/Directory.Build.props
- packages/Telephony/Microsoft.Bot.Components.Telephony.csproj
Ignore NU5048 to allow packages to be built locally. This was being overwritten by a second NoWarn clause in Directory.Build.props.
- Ignore NU5048 to allow packages to be built locally. This was being overwritten by a second NoWarn clause in Directory.Build.props.
- Always generate Telephony package in local build
- Ensure Microsoft.Bot.Component.sln builds successfully and Telephony package can be generated.
#minor
> chore: Ignore NU5048 to allow packages to be built locally

- packages/Telephony/Actions/BatchFixedLengthInput.cs
- packages/Telephony/Actions/BatchTerminationCharacterInput.cs
- packages/Telephony/Common/CommandDialog{T}.cs
- packages/Telephony/Common/RegexAggregatorInput.cs
- packages/Telephony/Readme.md
- packages/Telephony/Schemas/Microsoft.Telephony.BatchFixedLengthInput.schema
- packages/Telephony/Schemas/Microsoft.Telephony.BatchTerminationCharacterInput.schema
- packages/Telephony/Schemas/Microsoft.Telephony.PauseRecording.schema
- packages/Telephony/Schemas/Microsoft.Telephony.PauseRecording.uischema
- packages/Telephony/Schemas/Microsoft.Telephony.ResumeRecording.schema
- packages/Telephony/Schemas/Microsoft.Telephony.ResumeRecording.uischema
- packages/Telephony/Schemas/Microsoft.Telephony.StartRecording.schema
- packages/Telephony/Schemas/Microsoft.Telephony.StartRecording.uischema
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/BatchInputTests.cs
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_FixedLengthBaseScenario.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_FixedLength_WithTangent_InterruptionEnabled_EventInterrupt.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_TerminationBaseScenario.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_Termination_WithTangent_InterruptionEnabled_EventInterrupt.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/RecordingTests/Recording_BaseScenario.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Microsoft.Bot.Components.Telephony.Tests.csproj
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/RecordingTests.cs
Add reliability fixes to the Telephony package 
1. Set interruptions to false in recording / DTMF actions
2. CommandDialogs - disable interruptions when the incoming activity is a commandResult with the expected name
3. DTMF - process incoming activity only if its a message
1. Updated tests to mark interruptions as false by default
2. Verified that all tests work after the changes
readme.md updated.
#minor
> chore: Telephony: Improve AllowInterruptions related behavior for recording actions 

- build/yaml/functional/deployBotResources/js/evaluateDependenciesVariables.yml
While the standard botbuilder-js packages tagged next use `dev` in the version suffix, the botbuilder-dialogs-adaptive-runtime-integration-express uses `dev.preview`. This caused a bug in the functional tests pipeline where it couldn't find a match for the appropriate preview package and failed in the JS stages. This PR resolves that by only looking for the version of that specific package when determining what to apply to the functional test bots.
#minor
> build: resolve botbuilder-adaptive-runtime version sourcing in js

- build/yaml/templates/nuget-versioning-steps.yml
The merge from #1231 introduced some duplicate code in one of the yaml pipelines that doesn't allow any of them to be run. This reverts it back to a working state. Validated on the HelpAndCancel package (tests both nuget and npm variations)
#minor
> build: revert pipelines bug introduced in #1231

- generators/generator-bot-core-assistant/package.json
- generators/generator-bot-core-language/package.json
- generators/generator-bot-empty/package.json
- generators/generator-bot-enterprise-assistant/package.json
- generators/generator-bot-enterprise-calendar/package.json
- generators/generator-bot-enterprise-people/package.json
- yarn.lock
Published RC generators need to point to a published Adaptive Bot generator, not the version set in workspace. Without it, generators will work locally but not when published on npm.
#minor
> chore: bump generator dependencies to published adaptive bot generator

- generators/generator-bot-core-assistant/package.json
- generators/generator-bot-core-language/package.json
- generators/generator-bot-empty/package.json
- generators/generator-bot-enterprise-assistant/package.json
- generators/generator-bot-enterprise-calendar/package.json
- generators/generator-bot-enterprise-people/package.json
- yarn.lock
Revert #1283, setting adaptive generator references to `workspace:^1.2.0`
#minor
> chore: set adaptive bot generator refenences to stable

- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/CreateEventDialog/CreateEventDialog.dialog
- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/GetContactsDialog/GetContactsDialog.dialog
- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/ListDialog/ListDialog.dialog
- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/ResolveDateTimeDialog/ResolveDateTimeDialog.dialog
- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/UpdateEventDialog/UpdateEventDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/CancelEventDialog/CancelEventDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/CreateEventDialog/CreateEventDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/CreateEventDialog/language-generation/en-us/CreateEventDialog.en-us.lg
- skills/declarative/Calendar/Calendar/dialogs/GetContactsDialog/GetContactsDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/GetEventsDialog/GetEventsDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/ListDialog/ListDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/ResolveDateTimeDialog/ResolveDateTimeDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/UpdateEventDialog/UpdateEventDialog.dialog
This PR renamed all the foreach loop index and value variables to be unique as required by version 4.15.1 of the SDK. In this SDK version, the foreach action has been redesigned to resolve stackoverflow exceptions thrown by the previous implementation and improve bot performance. 
The foreach loop value and index variables should be unique within the dialog scope of the dialog so that external loop processing is not affected by internal loop processing. 
#minor
> fix: foreach bug in calendar for nested loop variables

- generators/generator-bot-adaptive/baseGenerator.js
- generators/generator-bot-enterprise-assistant/generators/app/index.js
A recent update to the globby library has caused the generator to erroneously double-process the root .sln file.
The root cause is that the previous versions passed in a single path variable in the form [wildcard, exclusion] but this ended up being concated into "wildcard/exclusion" which no longer works as expected.
This PR splits these parameters to avoid confusion.
Add an exclusion parameter explicitly. Change processing of globby params.
Fixes https://github.com/microsoft/BotFramework-Composer/issues/8927
> fix: make globby exclusion parameter explicit

- generators/generator-bot-core-assistant/package.json
- generators/generator-bot-core-language/package.json
- generators/generator-bot-empty/package.json
- generators/generator-bot-enterprise-assistant/package.json
- generators/generator-bot-enterprise-calendar/package.json
- generators/generator-bot-enterprise-people/package.json
- yarn.lock
Have to explicitly reference the published RC generators to validate. When this is in I will publish rc1 versions of the generator that point to the already published rc0 base bot generator. Enterprise Assistant will be published last at rc2, pointing to rc1 Calendar/People.
#minor
> chore: explicitly reference published 1.2.2-rc0 for adaptive bot generator

- generators/generator-bot-core-assistant/package.json
- generators/generator-bot-core-language/package.json
- generators/generator-bot-empty/package.json
- generators/generator-bot-enterprise-assistant/package.json
- generators/generator-bot-enterprise-calendar/package.json
- generators/generator-bot-enterprise-people/package.json
- yarn.lock
After this we can publish generators at 1.2.2@latest
#minor
> chore: revert generator dependencies to point to 1.2.2

- packages/Telephony/Actions/CallTransfer.cs
- packages/Telephony/Actions/SerialNumberInput.cs
- packages/Telephony/Actions/SerialNumberPattern.cs
- packages/Telephony/Actions/SerialNumberTextGroup.cs
- packages/Telephony/Schemas/Microsoft.Telephony.SerialNumberInput.schema
- packages/Telephony/Schemas/Microsoft.Telephony.SerialNumberInput.uischema
- packages/Telephony/TelephonyBotComponent.cs
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/SerialNumberInputTests/SerialNumberInput_BaseScenario.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/SerialNumberInputTests/SerialNumberInput_HappyPath.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/SerialNumberInputTests/SerialNumberInput_WithInterruption.test.dialog
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/SerialNumberInputTests.cs
Added  SerialNumberPattern and SerialNumberInput dialog to post process STT result for serial numbers
Post processing of result returned from speech for recognizing serial number patterns.
Classes to specify patterns for serial numbers and replace input received from STT.
> feat: Serial number post processing for STT

- generators/generator-bot-core-qna/README.md
Close #1324 
QnA template in composer is dependent on the readme hosted in components repo, this was previously removed as the template generator code itself is not used.
Related Composer code: https://github.com/microsoft/BotFramework-Composer/blob/01ccbcee840d5b8fe40fbde513956ad919f10317/Composer/packages/server/src/controllers/asset.ts#L127
> fix: add qna template readme back in

- generators/generator-bot-enterprise-people/generators/app/templates/dialogs/ListDialog/ListDialog.dialog
- generators/generator-bot-enterprise-people/generators/app/templates/dialogs/ListDialog/language-generation/en-us/ListDialog.en-us.lg
- skills/declarative/People/People/dialogs/ListDialog/ListDialog.dialog
- skills/declarative/People/People/dialogs/ListDialog/language-generation/en-us/ListDialog.en-us.lg
Resolves issue where turn.items is lost when ListDialog is interrupted
> fix: People list dialog error on interruption

- build/ExtractCompressNuGet.ps1
Fixes #minor
ExtractCompressNuGet.ps1 has outdated commented-out powershell patching code. 
This cleans it up.
> chore: Clean up ExtractCompressNuGet.ps1 in botframework-components

- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/RespondToEventDialog/RespondToEventDialog.dialog
- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/RespondToEventDialog/language-generation/en-us/RespondToEventDialog.en-us.lg
- packages/Graph/Models/CalendarSkillEventModel.cs
- skills/declarative/Calendar/Calendar/dialogs/RespondToEventDialog/RespondToEventDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/RespondToEventDialog/language-generation/en-us/RespondToEventDialog.en-us.lg
Fixes #1340
This PR fixes the error thrown when marking an event as tentative.
It was trying to send a response when the event's organizer had disabled the responses for the event. 
The same fix was applied to accept and decline event actions.
Also, it fixes the error thrown when the organizer tries to respond to its own event.
- Updated `RespondToEventDialog.dialog`:
- Moving the actions inside the _elseActions_ block in the **_event.isOrganizer_** condition.
- Adding a condition to evaluate **_event.responseRequested_** property before sending the responses.
- Passing the **_event_** property instead of only the **_event.Id_** to update the event.
- Updated `RespondToEventDialog.en-us.lg` including 3 new activities in the case the event's responses are disabled.
- Updated …
> fix: [#1340] Calendar Skill - Marking an event tentative throws an error to the user

- generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/GetEventsDialog/GetEventsDialog.dialog
- skills/declarative/Calendar/Calendar/dialogs/GetEventsDialog/GetEventsDialog.dialog
Fixes #1338
This PR fixes the error thrown after clicking on an adaptive card after confirming the creation of a new event.
It was trying to get the event's data but the eventId was unavailable.
- Updated the if condition in **_GetEventsdialog_** to consider both null and empty values. If the _eventId_ is not empty, trigger the _GetEventById_ event, otherwise, trigger the _GetEvents_ event.
These images show the error thrown before and the new behavior after the changes.
> fix: [#1338] Calendar Skill - Old adaptive card buttons trigger junk response

- packages/Telephony/Actions/TimeoutChoiceInput.cs
- packages/Telephony/TelephonyBotComponent.cs
Fixes #1380 
This PR registers BotWithLookup as the IBot implementation instead of the AdaptiveDialogBot that comes as default for a composer default. This is because we need to store a reference to the OnTurnAsync method of the AdaptiveDialogBot, so unless we register BotWithLookup, the constructor won't be called and OnTurn will be set to null.
No changes in functionality. Fixing a DI issue.
> fix: Register BotWithLookup to fix ArgumentNullException for OnTurn

- packages/Telephony/Actions/TimeoutChoiceInput.cs
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/TimeoutChoiceInputTests.cs
Fixes #1393: Default value bug in TimeoutChoiceInput
We are currently updating the MaxTurnCount instead of this.turnCount for the timer workflow which is affecting other conversations due to MaxTurnCount being a global value.
Update this.turnCount instead of MaxTurnCount so the changes are local to the action
Added tests to check for the turnCount being updated
> fix: Update the current turn count instead of MaxTurnCount in TimeoutChoiceInput

- build/yaml/templates/nuget-signing-steps.yml
Current ESRP signing tasks in Components pipelines are the old version 1. This is not compatible with later Windows versions.
close [https://github.com/microsoft/botframework-components/issues/1402](https://github.com/microsoft/botframework-components/issues/1402)
> chore: Update esrp tasks to v2 for Components pipelines

- packages/AdaptiveCards/Microsoft.Bot.Components.AdaptiveCards.csproj
- packages/Graph/Microsoft.Bot.Components.Graph.csproj
- packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec
- packages/Recognizers/CustomQuestionAnswering/Microsoft.Bot.Components.Recognizers.CustomQuestionAnsweringRecognizer.csproj
- packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj
- packages/Telephony/Microsoft.Bot.Components.Telephony.csproj
- packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec
- skills/csharp/calendarskill/CalendarSkill.csproj
- skills/declarative/Calendar/Calendar/Calendar.csproj
- skills/declarative/People/People/People.csproj
- tests/functional/Libraries/TranscriptConverter/TranscriptConverter.csproj
- tests/functional/Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj
- tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Microsoft.Bot.Components.Telephony.Tests.csproj
- tests/unit/packages/Teams/dotnet/Microsoft.Bot.Components.Teams.Tests.csproj
- tests/unit/skills/calendar/Microsoft.Bot.Dialogs.Tests.Skills.Calendar.csproj
- tests/unit/skills/common/Microsoft.Bot.Dialogs.Tests.Common.csproj
- tests/unit/skills/people/Microsoft.Bot.Dialogs.Tests.Skills.People.csproj
#minor
Vulnerability alert title: Governed repositories microsoft/botframework-components main CVE-2021-24112
Web page: [FuseLabs](https://fuselabs.visualstudio.com/)/[SDK_v4](https://fuselabs.visualstudio.com/SDK_v4)/[Compliance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)/[Component Governance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)
Critical severity alert: Remote code execution vulnerability exists when parsing certain types of graphics files. This vulnerability only exists on systems running on MacOS or Linux.
Upgrade System.Drawing.Common from 4.7.0 to 4.7.2
Dependency tree: 
- Microsoft.Bot.Components.Graph 1.1.2
- Microsoft.Bot.Builder.Dialogs.Adaptive.Runtime 4.17.1 (a botbuilder-dotnet package)
- …
> fix: Component Governance security vulnerability for System.Drawing.Common 4.7.0

- generators/generator-bot-adaptive/README.md
Fixes #minor
This readme is also published to npmjs here: [https://www.npmjs.com/package/@microsoft/generator-bot-adaptive?activeTab=readme](https://www.npmjs.com/package/@microsoft/generator-bot-adaptive?activeTab=readme)
I could not find the intended target of the  "our documentation" link, so I deleted that.
> fix: Two broken links in readme

- package.json
- yarn.lock
Fixes #minor
Vulnerability alert title: Governed repositories microsoft/botframework-components main CVE-2022-0235
Web page: [FuseLabs](https://fuselabs.visualstudio.com/)/[SDK_v4](https://fuselabs.visualstudio.com/SDK_v4)/[Compliance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)/[Component Governance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)
High severity alert: node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor
Upgrade node-fetch from 2.6.1 to 2.6.7
The current PR includes the fixes in these PRs. If you merge this one, you don't need to merge these.
Upgrade to "adal-node": "0.2.4" 
Upgrade to "@xmldom/xmldom": "0.8.6"
Upgrade to "axios": "1.2.1"
Upgrade to "@azure/identity": "3.1.2"
Upgrade to …
> fix: Component Governance security vulnerability for node-fetch 2.6.1

- package.json
- yarn.lock
Fixes #minor
Vulnerability alert title: Governed repositories microsoft/botframework-components main CVE-2022-0155, CVE-2022-0155, CVE-2021-3749
Web page: [FuseLabs](https://fuselabs.visualstudio.com/)/[SDK_v4](https://fuselabs.visualstudio.com/SDK_v4)/[Compliance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)/[Component Governance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)
High severity alerts: 
follow-redirects is vulnerable to Exposure of Private Personal Information to an Unauthorized Actor
Upgrade follow-redirects to 1.14.7
axios before v0.21.2 is vulnerable to Inefficient Regular Expression Complexity.
Upgrade axios from 0.21.1 to 0.21.2
A dependency tree snippet:
```
@microsoft/botframework-components@ …
```
> fix: Component Gov vulnerability for follow-redirects < 1.14.7 and axios 0.21.1

- build/yaml/pipelines/generator-bot-adaptive.yml
- build/yaml/pipelines/generator-bot-core-assistant.yml
- build/yaml/pipelines/generator-bot-core-language.yml
- build/yaml/pipelines/generator-bot-empty.yml
- build/yaml/pipelines/generator-bot-enterprise-assistant.yml
- build/yaml/pipelines/generator-bot-enterprise-calendar.yml
- build/yaml/pipelines/generator-bot-enterprise-people.yml
- generators/generator-bot-adaptive/generators/app/index.js
- generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
- generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj
- generators/generator-bot-adaptive/test/dotnet-functions.test.js
Addresses #1160
#minor
This PR migrates the bot generators to `NET6` as done for the SDK samples. 
Also, it upgrades the `AzureFunctionsVersion to 4` as Azure will stop supporting version 3 of the runtime soon ([more info](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=v4&pivots=programming-language-csharp)).
Finally, it updates the `vmImage` in the yamls that execute the generators.
- Change netcoreapp3.1 with net6.0 in the base generator template.
- Upgrade `Microsoft.AspNetCore.Mvc.NewtonsoftJson` references to version 6.0.7.
- Upgrade `Microsoft.NET.Sdk.Functions` reference to version 4.1.3.
- Upgrade `AzureFunctionsVersion` from 3 to 4.
- Update the `vmImage` in the yamls that execute the generators.
Here we can see some of the generated bots working …
> fix: [#1160] Generated bots can't run in dotnet 5.0 - Migrate Generators to NET6

- skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj
- skills/csharp/experimental/automotiveskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
- skills/csharp/experimental/bingsearchskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/eventskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/eventskill/EventSkill.csproj
- skills/csharp/experimental/hospitalityskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj
- skills/csharp/experimental/itsmskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/itsmskill/ITSMSkill.csproj
- skills/csharp/experimental/musicskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/musicskill/MusicSkill.csproj
- skills/csharp/experimental/newsskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/newsskill/NewsSkill.csproj
- skills/csharp/experimental/phoneskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/phoneskill/PhoneSkill.csproj
- skills/csharp/experimental/restaurantbookingskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj
- skills/csharp/experimental/weatherskill/Deployment/Scripts/publish.ps1
- skills/csharp/experimental/weatherskill/WeatherSkill.csproj
- skills/csharp/tests/hospitalityskill.tests/HospitalitySkill.Tests.csproj
- skills/csharp/tests/itsmskill.tests/ITSMSkill.Tests.csproj
- skills/csharp/tests/musicskill.Tests/MusicSkill.Tests.csproj
- skills/csharp/tests/phoneskill.tests/PhoneSkill.Tests.csproj
- skills/csharp/tests/weatherSkill.tests/WeatherSkill.Tests.csproj
Addresses #1160
#minor
This PR migrates the experimental skills projects to `NET6`. 
- Change netcoreapp3.1 with net6.0 in all experimental skill projects and test projects.
- Upgrade `Microsoft.AspNetCore.Mvc.NewtonsoftJson` references to version 6.0.7.
Here we can see the unit tests passing after the changes:
> fix: [#1160] Generated bots can't run in dotnet 5.0 - Migrate Experimental to NET6

- package.json
- yarn.lock
Fixes #1463
This PR adds the async versions corresponding to the libraries that depend on it according to their versions that have the vulnerability issue fixed.
- Add async version 2.6.4 in package.json for the libraries that use async 2.x 
- Add async version 3.2.4 in package.json for the libraries that use async 3.x 
The following image shows the result of the pipeline that generates the yarn.lock working successfully.
> fix: [#1463] PR's failing lint

- yarn.lock
#minor
This PR fixes the following error when trying to run `yarn install`:
_Type Error: Cannot read properties of undefined (reading 'toUpperCase')_ 
- Removed `semver@npm:^7.3.8` unnecessary addition from _yarn.lock_ file.
> fix: Components/Yarn assistance - yarn install error

- packages/Recognizers/ConversationLanguageUnderstanding/dotnet/CLU/CluAdaptiveRecognizer.cs
- packages/Recognizers/ConversationLanguageUnderstanding/dotnet/CLU/CluMainRecognizer.cs
- packages/Recognizers/ConversationLanguageUnderstanding/dotnet/README.md
Fixes #minor
Remove LUIS leftovers from CLU recognizer package and update Readme.
- Remove LUIS constants leftovers from CLU recognizer classes (CLUMainRecognizer & CLUAdaptiveRecognizer). 
- Update Readme to include only necessary parameters expected to be passed from Bot Composer. 
No need for new unit tests. After the minor changes the existing unit tests are still passing.
> fix: Remove LUIS leftovers from CLU recognizer package and update Readme.

- packages/Recognizers/ConversationLanguageUnderstanding/dotnet/CluExtensions.cs
Fixes #1510 
Currently, when the CLU Recognizer gets the intent result from CLU, it parses the confidence score (expected to be between 0-1) without respect to the user's culture. This causes issues with languages where a `.` decimal point is not used to represent fractional numbers. In some cultures, such as Spanish or French, decimal values are represented with different characters, such as a `,`. Confidence scores for these cultures are currently parsed incorrectly and result in confidence score values that are out of bounds.
- In `CluExtensions.cs` on line 25, change `double.Parse` to use `CultureInfo.CurrentCulture` instead of `CultureInfo.InvariantCulture`.
- Covered by existing tests. The parsed confidence score should be valid for any culture. Tests passing successfully.
- Also …
> fix: Change Confidence Score Parse in CLU Recognizer to use Current Culture

- tests/unit/packages/Recognizers/js/package.json
- tests/unit/packages/Recognizers/js/tests/cluApplication.test.ts
- tests/unit/packages/Recognizers/js/tests/cluExtensions.test.ts
- tests/unit/packages/Recognizers/js/tests/cluRecognizerOptions.test.ts
- tests/unit/packages/Recognizers/js/tests/cluRecognizerOptionsBase.test.ts
- tests/unit/packages/Recognizers/js/tests/defaultHttpClientFactory.test.ts
- tests/unit/packages/Recognizers/js/tsconfig.json
- yarn.lock
Fixes #1514
> **_This PR depends on #1518 which contains the JS CLU Recognizer_, and must be merged after this one.**
This PR ports the [CLU Recognizer's unit tests](https://github.com/microsoft/botframework-components/tree/main/tests/unit/packages/Recognizers/dotnet) from .NET to JS.
- Added new `js` folder under the `tests/unit/packages/Recognizers` directory.
- Added config files `tsconfig.json` and `package.json` for the new test project.
- Added unit tests for the following classes:
- CluApplication
- CluExtensions
- CluRecognizerOptions
- CluRecognizerOptionsBase
- DefaultHttpClientFactory
This image shows the new unit tests passing.
> feat: [#1514] Port JS CLU Recognizer unit tests

- tests/unit/packages/Recognizers/js/tests/cluRecognizerOptions.test.ts
- tests/unit/packages/Recognizers/js/tests/cluRecognizerOptionsBase.test.ts
#minor
This PR fixes 2 remaining lint issues in the new JS CLU Recognizer's unit tests.
- Applied lint autofix on:
- cluRecognizerOptions.test.ts
- cluRecognizerOptionsBase.test.ts
> fix: lint issues in clu recognizer tests

- packages/Recognizers/ConversationLanguageUnderstanding/dotnet/README.md
- packages/Recognizers/ConversationLanguageUnderstanding/js/README.md
fixes [#9683](https://github.com/microsoft/BotFramework-Composer/issues/9683)
> docs: Fix CLU package name in readme
