skills/csharp/emailskill/EmailSkill.csproj, skills/csharp/todoskill/ToDoSkill.csproj
update email and todo skill to rc4 and daily248 for solutions lib
=> update email and todo skill to rc4

skills/csharp/experimental/itsmskill/Dialogs/CloseTicketDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/MainDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/ShowKnowledgeDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/ShowTicketDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs, skills/csharp/experimental/itsmskill/Dialogs/UpdateTicketDialog.cs, skills/csharp/experimental/itsmskill/Models/Actions/ActionNames.cs, skills/csharp/experimental/itsmskill/Models/Actions/ActionResult.cs, skills/csharp/experimental/itsmskill/Models/Actions/CloseTicketInput.cs, skills/csharp/experimental/itsmskill/Models/Actions/CreateTicketInput.cs, skills/csharp/experimental/itsmskill/Models/Actions/IActionInput.cs, skills/csharp/experimental/itsmskill/Models/Actions/ShowKnowledgeInput.cs, skills/csharp/experimental/itsmskill/Models/Actions/ShowTicketInput.cs, skills/csharp/experimental/itsmskill/Models/Actions/UpdateTicketInput.cs, skills/csharp/experimental/itsmskill/Models/EndFlowResult.cs, skills/csharp/experimental/itsmskill/Models/SkillState.cs, skills/csharp/tests/itsmskill.tests/Flow/KnowledgeShowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/SkillTestBase.cs, skills/csharp/tests/itsmskill.tests/Flow/TicketCloseFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/TicketCreateFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/TicketShowFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/TicketUpdateFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/Utterances/KnowledgeShowUtterances.cs, skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketCloseUtterances.cs, skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketCreateUtterances.cs, skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketShowUtterances.cs, skills/csharp/tests/itsmskill.tests/Flow/Utterances/TicketUpdateUtterances.cs
Add action code
Use EndFlowResult to break underlying flows
Add corresponding ones
=> [ITSM] add action code

skills/csharp/experimental/automotiveskill/Dialogs/AutomotiveSkillDialogBase.cs, skills/csharp/experimental/automotiveskill/Dialogs/MainDialog.cs, skills/csharp/experimental/automotiveskill/Dialogs/VehicleSettingsDialog.cs, skills/csharp/experimental/automotiveskill/Models/Actions/ActionResult.cs, skills/csharp/experimental/automotiveskill/Models/Actions/SettingInfo.cs, skills/csharp/experimental/automotiveskill/Models/AutomotiveSkillState.cs, skills/csharp/experimental/automotiveskill/Utilities/SettingFilter.cs, skills/csharp/experimental/automotiveskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/automotiveskill/wwwroot/manifest/manifest-1.1.json
=> [automotive] action code

skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailTexts.de-de.lg, skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailTexts.es-es.lg, skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailTexts.fr-fr.lg, skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailTexts.it-it.lg, skills/csharp/emailskill/Responses/DeleteEmail/DeleteEmailTexts.zh-cn.lg, skills/csharp/emailskill/Responses/FindContact/FindContactTexts.de-de.lg, skills/csharp/emailskill/Responses/FindContact/FindContactTexts.es-es.lg, skills/csharp/emailskill/Responses/FindContact/FindContactTexts.fr-fr.lg, skills/csharp/emailskill/Responses/FindContact/FindContactTexts.it-it.lg, skills/csharp/emailskill/Responses/FindContact/FindContactTexts.zh-cn.lg, skills/csharp/emailskill/Responses/Main/MainDialogTexts.de-de.lg, skills/csharp/emailskill/Responses/Main/MainDialogTexts.es-es.lg, skills/csharp/emailskill/Responses/Main/MainDialogTexts.fr-fr.lg, skills/csharp/emailskill/Responses/Main/MainDialogTexts.it-it.lg, skills/csharp/emailskill/Responses/Main/MainDialogTexts.zh-cn.lg, skills/csharp/emailskill/Responses/SendEmail/SendEmailTexts.de-de.lg, skills/csharp/emailskill/Responses/SendEmail/SendEmailTexts.es-es.lg, skills/csharp/emailskill/Responses/SendEmail/SendEmailTexts.fr-fr.lg, skills/csharp/emailskill/Responses/SendEmail/SendEmailTexts.it-it.lg, skills/csharp/emailskill/Responses/SendEmail/SendEmailTexts.zh-cn.lg, skills/csharp/emailskill/Responses/Shared/SharedTexts.de-de.lg, skills/csharp/emailskill/Responses/Shared/SharedTexts.es-es.lg, skills/csharp/emailskill/Responses/Shared/SharedTexts.fr-fr.lg, skills/csharp/emailskill/Responses/Shared/SharedTexts.it-it.lg, skills/csharp/emailskill/Responses/Shared/SharedTexts.zh-cn.lg, skills/csharp/emailskill/Responses/ShowEmail/ShowEmailTexts.de-de.lg, skills/csharp/emailskill/Responses/ShowEmail/ShowEmailTexts.es-es.lg, skills/csharp/emailskill/Responses/ShowEmail/ShowEmailTexts.fr-fr.lg, skills/csharp/emailskill/Responses/ShowEmail/ShowEmailTexts.it-it.lg, skills/csharp/emailskill/Responses/ShowEmail/ShowEmailTexts.zh-cn.lg
some lg files didn't apply with now lg format
=> [Email] fix LG files

skills/csharp/emailskill/Services/BotServices.cs, skills/csharp/todoskill/Services/BotServices.cs
=> [Email][Todo] Fix knowledge base config

skills/csharp/pointofinterestskill/Adapters/DefaultAdapter.cs, skills/csharp/pointofinterestskill/Dialogs/CancelRouteDialog.cs, skills/csharp/pointofinterestskill/Dialogs/FindParkingDialog.cs, skills/csharp/pointofinterestskill/Dialogs/FindPointOfInterestDialog.cs, skills/csharp/pointofinterestskill/Dialogs/GetDirectionsDialog.cs, skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs, skills/csharp/pointofinterestskill/Dialogs/RouteDialog.cs, skills/csharp/pointofinterestskill/Services/BotServices.cs, skills/csharp/pointofinterestskill/Utilities/LocaleTemplateManagerWrapper.cs
* Fix Knowledgebases
* Rename to templateManager & GenerateActivity
Note it should be used against VA with 4.8.0-rc5
=> [POI] fix Knowledgebases, rename

skills/csharp/calendarskill/Services/BotServices.cs, skills/csharp/experimental/automotiveskill/Services/BotServices.cs
=> [calendar/auto] fix Knowledgebases config

skills/csharp/calendarskill/CalendarSkill.csproj, skills/csharp/calendarskill/Dialogs/MainDialog.cs, skills/csharp/emailskill/Dialogs/MainDialog.cs, skills/csharp/emailskill/EmailSkill.csproj, skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj, skills/csharp/experimental/automotiveskill/Dialogs/MainDialog.cs, skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj, skills/csharp/experimental/bingsearchskill/Dialogs/MainDialog.cs, skills/csharp/experimental/eventskill/Dialogs/MainDialog.cs, skills/csharp/experimental/eventskill/EventSkill.csproj, skills/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs, skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj, skills/csharp/experimental/itsmskill/Dialogs/MainDialog.cs, skills/csharp/experimental/itsmskill/ITSMSkill.csproj, skills/csharp/experimental/musicskill/Dialogs/MainDialog.cs, skills/csharp/experimental/musicskill/MusicSkill.csproj, skills/csharp/experimental/newsskill/Dialogs/MainDialog.cs, skills/csharp/experimental/newsskill/NewsSkill.csproj, skills/csharp/experimental/phoneskill/Dialogs/MainDialog.cs, skills/csharp/experimental/phoneskill/PhoneSkill.csproj, skills/csharp/experimental/restaurantbookingskill/Dialogs/MainDialog.cs, skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj, skills/csharp/experimental/weatherskill/Dialogs/MainDialog.cs, skills/csharp/experimental/weatherskill/WeatherSkill.csproj, skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj, skills/csharp/todoskill/Dialogs/MainDialog.cs, skills/csharp/todoskill/Responses/Main/ToDoMainActivities.es-es.lg, skills/csharp/todoskill/ToDoSkill.csproj
Update all skills to 4.8.1
Update FinalStepAsync of all MainDialogs to not explicitly return EndOfConversation.
=> Update all skills to 4.8.1

skills/csharp/emailskill/wwwroot/manifest/manifest-1.1.json
activities is missing
close: https://github.com/microsoft/botframework-skills/issues/81
related: https://github.com/microsoft/botframework-skills/pull/30
=> [Email] fix email manifest

skills/csharp/calendarskill/Deployment/Resources/LU/de-de/Calendar.lu, skills/csharp/calendarskill/Deployment/Resources/LU/en-us/Calendar.lu, skills/csharp/calendarskill/Deployment/Resources/LU/es-es/Calendar.lu, skills/csharp/calendarskill/Deployment/Resources/LU/fr-fr/Calendar.lu, skills/csharp/calendarskill/Deployment/Resources/LU/it-it/Calendar.lu, skills/csharp/calendarskill/Deployment/Resources/LU/zh-cn/Calendar.lu
The .lu file in master branch of botframework-solution repo has some conflicts with the current branch. We need to merge it.
=> [Calendar] merge calendar .lu in bf-solution repo master branch

skills/csharp/calendarskill/Deployment/Scripts/enable_findmeetingroom.ps1, skills/csharp/calendarskill/Deployment/Scripts/msgraph_functions.ps1
=> [calendar] book meeting room script update

skills/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Bots/DefaultActivityHandler.cs, skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/tests/hospitalityskill.tests/Flow/LateCheckOutFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/KnowledgeShowTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/FindParkingDialogTests.cs
Related #22 #77
POI, ITSM, Hospitality:
* use TeamsActivityHandler, update InterruptDialogAsync
* add tests
=> use TeamsActivityHandler, update InterruptDialogAsync

skills/csharp/experimental/weatherskill/WeatherSkill.csproj
Fix https://github.com/microsoft/botframework-skills/issues/96
=> [Weather] Update json files' copy options

skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs
=> [POI] check null luis result

skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj
Some lg files are not set as copy if never
=> [Bing Search] Set lg files as copy if never

skills/csharp/experimental/newsskill/Dialogs/MainDialog.cs
Close: https://github.com/microsoft/botframework-skills/issues/108
=> [News] Fix FindArticles action exception

skills/csharp/emailskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/emailskill/wwwroot/manifest/manifest-1.1.json
close: https://github.com/microsoft/botframework-skills/issues/104
=> [Email] fix manifest

skills/csharp/experimental/restaurantbookingskill/.filenesting.json, skills/csharp/experimental/restaurantbookingskill/Responses/Main/RestaurantBookingMainResponses.cs, skills/csharp/experimental/restaurantbookingskill/Responses/Main/RestaurantBookingMainResponses.tt, skills/csharp/experimental/restaurantbookingskill/Responses/Shared/BotStrings.cs, skills/csharp/experimental/restaurantbookingskill/Responses/Shared/BotStrings.tt, skills/csharp/experimental/restaurantbookingskill/Responses/Shared/RestaurantBookingSharedResponses.cs, skills/csharp/experimental/restaurantbookingskill/Responses/Shared/RestaurantBookingSharedResponses.tt, skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj, skills/csharp/experimental/weatherskill/Responses/Main/MainResponses.cs, skills/csharp/experimental/weatherskill/Responses/Main/MainResponses.tt, skills/csharp/experimental/weatherskill/Responses/Shared/SharedResponses.cs, skills/csharp/experimental/weatherskill/Responses/Shared/SharedResponses.tt, skills/csharp/experimental/weatherskill/WeatherSkill.csproj, skills/csharp/todoskill/.filenesting.json, skills/csharp/todoskill/Responses/AddToDo/AddToDoResponses.cs, skills/csharp/todoskill/Responses/AddToDo/AddToDoResponses.tt, skills/csharp/todoskill/Responses/DeleteToDo/DeleteToDoResponses.cs, skills/csharp/todoskill/Responses/DeleteToDo/DeleteToDoResponses.tt, skills/csharp/todoskill/Responses/Main/ToDoMainResponses.cs, skills/csharp/todoskill/Responses/Main/ToDoMainResponses.tt, skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.cs, skills/csharp/todoskill/Responses/MarkToDo/MarkToDoResponses.tt, skills/csharp/todoskill/Responses/Shared/ToDoSharedResponses.cs, skills/csharp/todoskill/Responses/Shared/ToDoSharedResponses.tt, skills/csharp/todoskill/Responses/ShowToDo/ShowToDoResponses.cs, skills/csharp/todoskill/Responses/ShowToDo/ShowToDoResponses.tt, skills/csharp/todoskill/ToDoSkill.csproj
=> [ToDo/ Weather/ Restaurant Booking] Remove tt files

skills/csharp/todoskill/Dialogs/ShowToDoItemDialog.cs
Fix this issue when ListType is null: https://github.com/microsoft/botframework-skills/issues/100
=> [ToDo] Fix ShowToDo bug

skills/csharp/todoskill/Bots/DefaultActivityHandler.cs
Add TeamsActivityHandler: https://github.com/microsoft/botframework-skills/issues/22
=> [ToDo] Add TeamsActivityHandler

skills/csharp/emailskill/Dialogs/FindContactDialog.cs
=> [Email] fix exception

skills/csharp/calendarskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/calendarskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/emailskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/emailskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/automotiveskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/automotiveskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/bingsearchskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/bingsearchskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/eventskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/eventskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/hospitalityskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/hospitalityskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/itsmskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/itsmskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/musicskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/musicskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/newsskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/newsskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/phoneskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/phoneskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/restaurantbookingskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/restaurantbookingskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/experimental/weatherskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/weatherskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/todoskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/todoskill/wwwroot/manifest/manifest-1.1.json
Close #101
Fix boolean, array (https://json-schema.org/understanding-json-schema/reference/array.html)
=> fix version, boolean, array

skills/csharp/calendarskill/Bots/DefaultActivityHandler.cs, skills/csharp/calendarskill/Dialogs/MainDialog.cs, skills/csharp/calendarskill/Models/ActionInfos/EventInfo.cs, skills/csharp/tests/calendarskill.tests/Flow/CreateCalendarFlowTests.cs, skills/csharp/tests/calendarskill.tests/Flow/SummaryCalendarFlowTests.cs, skills/csharp/tests/calendarskill.tests/Flow/Utterances/CreateMeetingTestUtterances.cs, skills/csharp/tests/calendarskill.tests/Flow/Utterances/FindMeetingTestUtterances.cs
fix bug #102 #103 
add TeamsActivityHandler #22 cancel/logout #77 
add some test cases
=> [calendar] fix calendar issues

skills/csharp/experimental/restaurantbookingskill/Dialogs/MainDialog.cs, skills/csharp/experimental/weatherskill/Dialogs/MainDialog.cs, skills/csharp/todoskill/Dialogs/MainDialog.cs
https://github.com/microsoft/botframework-skills/issues/77
=> [ToDo/ Weather/ Restaurant Booking] Handle cancel/logout in skill mode

skills/csharp/experimental/eventskill/Dialogs/MainDialog.cs, skills/csharp/experimental/phoneskill/Bots/DefaultActivityHandler.cs, skills/csharp/experimental/phoneskill/Dialogs/MainDialog.cs, skills/csharp/tests/phoneskill.tests/Flow/InterruptionTests.cs, skills/csharp/tests/phoneskill.tests/Flow/PhoneSkillTestBase.cs
Support TeamsActivityHandler for Event and Phone skill. 
Update the Cancel/Logout handling
=> [Phone] TeamsActivityHandler support

skills/csharp/experimental/automotiveskill/Bots/DefaultActivityHandler.cs, skills/csharp/experimental/automotiveskill/Dialogs/MainDialog.cs, skills/csharp/experimental/musicskill/Bots/DefaultActivityHandler.cs, skills/csharp/experimental/musicskill/Dialogs/MainDialog.cs
=> [auto/music] update teamAcitivityHanlder and cancel&logout

skills/csharp/experimental/weatherskill/Dialogs/MainDialog.cs, skills/csharp/experimental/weatherskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/experimental/weatherskill/wwwroot/manifest/manifest-1.1.json
=> [Weather] Fix typo

skills/csharp/experimental/hospitalityskill/Bots/DefaultActivityHandler.cs, skills/csharp/experimental/hospitalityskill/Dialogs/MainDialog.cs, skills/csharp/experimental/hospitalityskill/Dialogs/RoomServiceDialog.cs, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.cs, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.de-de.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.es-es.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.fr-fr.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.it-it.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponses.zh-cn.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponsesTexts.de-de.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponsesTexts.es-es.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponsesTexts.fr-fr.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponsesTexts.it-it.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponsesTexts.lg, skills/csharp/experimental/hospitalityskill/Responses/Main/MainResponsesTexts.zh-cn.lg, skills/csharp/experimental/itsmskill/Dialogs/MainDialog.cs, skills/csharp/experimental/itsmskill/Responses/Main/MainResponses.cs, skills/csharp/experimental/itsmskill/Responses/Main/MainResponses.lg, skills/csharp/experimental/itsmskill/Responses/Main/MainResponsesTexts.lg, skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.Designer.cs, skills/csharp/experimental/itsmskill/Responses/Shared/SharedStrings.resx, skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/tests/hospitalityskill.tests/Flow/GeneralFlowTests.cs, skills/csharp/tests/hospitalityskill.tests/Flow/LateCheckOutFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/GeneralFlowTests.cs, skills/csharp/tests/itsmskill.tests/Flow/KnowledgeShowTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/FindParkingDialogTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/GeneralSkillFlowTests.cs
Fix miss {0} for string format, no FirstPromptMessage
Add tests
=> [POI][ITSM][H] fix

skills/csharp/pointofinterestskill/Dialogs/GetDirectionsDialog.cs, skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs, skills/csharp/pointofinterestskill/Models/PointOfInterestSkillState.cs, skills/csharp/pointofinterestskill/Models/StateProperties.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/GetDirectionsDialogTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestDialogTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestSkillTestBase.cs
Fix interrupt in GetDirections and skill mode
* Fix interrupt in GetDirections and skill mode
* Move ShouldInterrupt to TurnState
* Add tests
=> [POI] fix interrupt and add test

skills/csharp/experimental/phoneskill/Adapters/DefaultAdapter.cs, skills/csharp/experimental/phoneskill/Authentication/AllowedCallersClaimsValidator.cs, skills/csharp/experimental/phoneskill/Bots/DefaultActivityHandler.cs, skills/csharp/experimental/phoneskill/Common/ContactFilter.cs, skills/csharp/experimental/phoneskill/Common/IContactProvider.cs, skills/csharp/experimental/phoneskill/Dialogs/MainDialog.cs, skills/csharp/experimental/phoneskill/Dialogs/OutgoingCallDialog.cs, skills/csharp/experimental/phoneskill/Dialogs/PhoneSkillDialogBase.cs, skills/csharp/experimental/phoneskill/Models/Actions/ActionResult.cs, skills/csharp/experimental/phoneskill/Models/Actions/OutgoingCallRequest.cs, skills/csharp/experimental/phoneskill/PhoneSkill.csproj, skills/csharp/experimental/phoneskill/Services/BotServices.cs, skills/csharp/experimental/phoneskill/Services/GoogleAPI/GoogleContactProvider.cs, skills/csharp/experimental/phoneskill/Services/MSGraphAPI/GraphContactProvider.cs, skills/csharp/experimental/phoneskill/Startup.cs, skills/csharp/experimental/phoneskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/phoneskill/appsettings.json, skills/csharp/shared/SkillServiceLibrary/SkillServiceLibrary.csproj, skills/csharp/shared/SkillServiceLibrary/Utilities/ITurnContextEx.cs, skills/csharp/tests/SkillServiceLibrary.Fakes/SkillServiceLibrary.Fakes.csproj, skills/csharp/tests/SkillServiceLibrary.Tests/SkillServiceLibrary.Tests.csproj, skills/csharp/tests/phoneskill.tests/PhoneSkill.Tests.csproj, skills/csharp/tests/phoneskill.tests/TestDouble/MockLuisRecognizer.cs, skills/csharp/tests/phoneskill.tests/TestDouble/StubContactProvider.cs
Align to skill template.
Please refer to https://github.com/microsoft/botframework-skills/issues/124
=> [Phone] align to skill template

skills/csharp/calendarskill/Deployment/Scripts/enable_findmeetingroom.ps1
#120 
add migration tool to speed up importing data into cosmos-db
=> [calendar] update enable meeting room script

skills/csharp/experimental/itsmskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Adapters/DefaultAdapter.cs, skills/csharp/pointofinterestskill/Bots/DefaultActivityHandler.cs, skills/csharp/pointofinterestskill/Dialogs/CancelRouteDialog.cs, skills/csharp/pointofinterestskill/Dialogs/FindParkingDialog.cs, skills/csharp/pointofinterestskill/Dialogs/FindPointOfInterestDialog.cs, skills/csharp/pointofinterestskill/Dialogs/GetDirectionsDialog.cs, skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs, skills/csharp/pointofinterestskill/Dialogs/RouteDialog.cs, skills/csharp/pointofinterestskill/Models/ActionNames.cs, skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj, skills/csharp/pointofinterestskill/Responses/Main/POIMainResponses.de-de.lg, skills/csharp/pointofinterestskill/Responses/Main/POIMainResponses.es-es.lg, skills/csharp/pointofinterestskill/Responses/Main/POIMainResponses.fr-fr.lg, skills/csharp/pointofinterestskill/Responses/Main/POIMainResponses.it-it.lg, skills/csharp/pointofinterestskill/Responses/Main/POIMainResponses.lg, skills/csharp/pointofinterestskill/Responses/Main/POIMainResponses.zh-cn.lg, skills/csharp/pointofinterestskill/Services/BotServices.cs, skills/csharp/pointofinterestskill/Startup.cs, skills/csharp/pointofinterestskill/Utilities/Actions.cs, skills/csharp/pointofinterestskill/appsettings.json, skills/csharp/tests/pointofinterestskill.tests/Flow/Fakes/MockGeneralLuisRecognizer.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/Fakes/MockPointOfInterestLuisRecognizer.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/GeneralSkillFlowTests.cs, skills/csharp/tests/pointofinterestskill.tests/PointOfInterestSkill.Tests.csproj
Update to https://github.com/microsoft/botframework-solutions/commit/acdfdda8b1223f602ed279d2b6227197e9105218
* send WelcomeMessage in OnMembersAddedAsync as skill
* use IncludeInstanceData in Luis
=> [POI] update to latest

skills/csharp/emailskill/Adapters/DefaultAdapter.cs, skills/csharp/emailskill/Bots/DefaultActivityHandler.cs, skills/csharp/emailskill/Dialogs/DeleteEmailDialog.cs, skills/csharp/emailskill/Dialogs/EmailSkillDialogBase.cs, skills/csharp/emailskill/Dialogs/FindContactDialog.cs, skills/csharp/emailskill/Dialogs/ForwardEmailDialog.cs, skills/csharp/emailskill/Dialogs/MainDialog.cs, skills/csharp/emailskill/Dialogs/ReplyEmailDialog.cs, skills/csharp/emailskill/Dialogs/SendEmailDialog.cs, skills/csharp/emailskill/Dialogs/ShowEmailDialog.cs, skills/csharp/emailskill/EmailSkill.csproj, skills/csharp/emailskill/Services/BotServices.cs, skills/csharp/emailskill/Startup.cs, skills/csharp/emailskill/appsettings.json, skills/csharp/tests/emailskill.tests/Flow/Fakes/MockEmailLuisRecognizer.cs, skills/csharp/tests/emailskill.tests/Flow/Fakes/MockGeneralLuisRecognizer.cs
email skill align to skill template
=> [email] align to skill template

skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs, skills/csharp/experimental/itsmskill/appsettings.json, skills/csharp/experimental/phoneskill/Dialogs/PhoneSkillDialogBase.cs, skills/csharp/experimental/phoneskill/appsettings.json
Follow https://github.com/microsoft/botframework-skills/pull/149
=> [ITSM][Phone] add oauthCredentials

skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs, skills/csharp/shared/SkillServiceLibrary/Models/PointOfInterestModelSlim.cs
=> Return raw POI data via ChannelData to support Comcast integration

skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Models/ActionBaseInput.cs, skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.0.json, skills/csharp/pointofinterestskill/wwwroot/manifest/manifest-1.1.json, skills/csharp/tests/pointofinterestskill.tests/Flow/FindParkingDialogTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/GetDirectionsDialogTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestDialogTests.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindParkingUtterances.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/FindPointOfInterestUtterances.cs, skills/csharp/tests/pointofinterestskill.tests/Flow/Utterances/RouteFromXToYUtterances.cs
Add zipcode in action. It is a convenient way to provide location
=> [POI] add zipcode support

skills/declarative/calendarskill/calendarskill.dialog, skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/AcceptMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/language-generation/en-us/AcceptMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/BookMeetingRoom/BookMeetingRoom.dialog, skills/declarative/calendarskill/dialogs/BookMeetingRoom/language-generation/en-us/BookMeetingRoom.en-us.lg, skills/declarative/calendarskill/dialogs/DeleteMeetingDialog/DeleteMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/DeleteMeetingDialog/language-generation/en-us/DeleteMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/FindMeetingRoom/FindMeetingRoom.dialog, skills/declarative/calendarskill/dialogs/FindMeetingRoom/language-generation/en-us/FindMeetingRoom.en-us.lg, skills/declarative/calendarskill/dialogs/SearchMeetings/SearchMeetings.dialog, skills/declarative/calendarskill/dialogs/SearchMeetings/language-generation/en-us/SearchMeetings.en-us.lg, skills/declarative/calendarskill/dialogs/SearchMeetings/language-understanding/en-us/SearchMeetings.en-us.lu, skills/declarative/calendarskill/dialogs/SetDateTime/SetDateTime.dialog, skills/declarative/calendarskill/dialogs/SetDateTime/language-generation/en-us/SetDateTime.en-us.lg, skills/declarative/calendarskill/dialogs/SetDuration/SetDuration.dialog, skills/declarative/calendarskill/dialogs/SetDuration/language-generation/en-us/SetDuration.en-us.lg, skills/declarative/calendarskill/dialogs/SetTitle/SetTitle.dialog, skills/declarative/calendarskill/dialogs/SetTitle/language-generation/en-us/SetTitle.en-us.lg, skills/declarative/calendarskill/dialogs/UpdateMeetingDialog/UpdateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/UpdateMeetingDialog/language-generation/en-us/UpdateMeetingDialog.en-us.lg, skills/declarative/calendarskill/language-generation/en-us/calendarskill.en-us.lg, skills/declarative/calendarskill/language-understanding/en-us/calendarskill.en-us.lu, skills/declarative/calendarskill/settings/appsettings.json
An initial version for Accept/Delete/Update meeting and BookMeetingRoom.
=> [Calendar] Accept-Delete-Update and BookMeetingRoom

skills/csharp/Directory.Build.props, skills/csharp/calendarskill/CalendarSkill.csproj, skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj, skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj, skills/csharp/experimental/eventskill/EventSkill.csproj, skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj, skills/csharp/experimental/itsmskill/ITSMSkill.csproj, skills/csharp/experimental/musicskill/MusicSkill.csproj, skills/csharp/experimental/newsskill/NewsSkill.csproj, skills/csharp/experimental/phoneskill/PhoneSkill.csproj, skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj, skills/csharp/experimental/weatherskill/WeatherSkill.csproj, skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj, skills/csharp/tests/hospitalityskill.tests/HospitalitySkill.Tests.csproj, skills/csharp/tests/itsmskill.tests/ITSMSkill.Tests.csproj, skills/csharp/tests/musicskill.Tests/MusicSkill.Tests.csproj, skills/csharp/tests/phoneskill.tests/PhoneSkill.Tests.csproj, skills/csharp/tests/pointofinterestskill.tests/PointOfInterestSkill.Tests.csproj, skills/csharp/todoskill/ToDoSkill.csproj
follow up on Ted's comments. Move project reference StyleCop.Analyzers to shared Directory.Build.props.
Move project reference StyleCop.Analyzers to shared Directory.Build.props.
=> [Skills] Update Directory.Build.props and project files

skills/csharp/experimental/itsmskill/Content/Knowledge.pva.json, skills/csharp/experimental/itsmskill/Content/Ticket.pva.json, skills/csharp/experimental/itsmskill/Content/TicketUpdate.pva.json, skills/csharp/experimental/itsmskill/Content/TicketUpdateClose.pva.json, skills/csharp/experimental/itsmskill/Dialogs/CloseTicketDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/CreateTicketDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/ShowTicketDialog.cs, skills/csharp/experimental/itsmskill/Dialogs/SkillDialogBase.cs, skills/csharp/experimental/itsmskill/Dialogs/UpdateTicketDialog.cs
ActionSet will be rendered by container like this:
=> use special cards for pva

skills/declarative/todoskill/BotDesign.md, skills/declarative/todoskill/ToDoSkill.dialog, skills/declarative/todoskill/dialogs/AddToDo/AddToDo.dialog, skills/declarative/todoskill/dialogs/AddToDo/language-generation/en-us/AddToDo.en-us.lg, skills/declarative/todoskill/dialogs/AddToDo/language-understanding/en-us/AddToDo.en-us.lu, skills/declarative/todoskill/dialogs/DeleteInListOutlook/DeleteInListOutlook.dialog, skills/declarative/todoskill/dialogs/DeleteToDo/DeleteToDo.dialog, skills/declarative/todoskill/dialogs/DeleteToDo/language-generation/en-us/DeleteToDo.en-us.lg, skills/declarative/todoskill/dialogs/DeleteToDo/language-understanding/en-us/DeleteToDo.en-us.lu, skills/declarative/todoskill/dialogs/MarkToDo/MarkToDo.dialog, skills/declarative/todoskill/dialogs/ShowToDo/ShowToDo.dialog, skills/declarative/todoskill/dialogs/ShowToDo/language-generation/en-us/ShowToDo.en-us.lg, skills/declarative/todoskill/language-generation/en-us/common.en-us.lg
Use 3 different ways to handle interruption:
* Itself: show
* Separate list & content with reordering: add
* Unify to getinput: mark & delete
=> [DToDo] mirror delete from mark

skills/declarative/todoskill/ToDoSkill.dialog, skills/declarative/todoskill/dialogs/AddToDo/AddToDo.dialog, skills/declarative/todoskill/dialogs/AddToDo/language-generation/en-us/AddToDo.en-us.lg, skills/declarative/todoskill/dialogs/AddToDo/language-understanding/en-us/AddToDo.en-us.lu, skills/declarative/todoskill/dialogs/DeleteToDo/DeleteToDo.dialog, skills/declarative/todoskill/dialogs/DeleteToDo/language-generation/en-us/DeleteToDo.en-us.lg, skills/declarative/todoskill/dialogs/DeleteToDo/language-understanding/en-us/DeleteToDo.en-us.lu, skills/declarative/todoskill/dialogs/MarkToDo/MarkToDo.dialog, skills/declarative/todoskill/dialogs/MarkToDo/language-generation/en-us/MarkToDo.en-us.lg, skills/declarative/todoskill/dialogs/MarkToDo/language-understanding/en-us/MarkToDo.en-us.lu, skills/declarative/todoskill/dialogs/ShowToDo/ShowToDo.dialog, skills/declarative/todoskill/dialogs/ShowToDo/language-generation/en-us/ShowToDo.en-us.lg, skills/declarative/todoskill/language-generation/en-us/ToDoSkill.en-us.lg, skills/declarative/todoskill/language-generation/en-us/common.en-us.lg
=> [DToDo] use slottype for multiple refilling

skills/declarative/calendarskill/.gitignore, skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/AcceptMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/language-generation/en-us/AcceptMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/BookMeetingRoom/BookMeetingRoom.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/CreateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingRequest/CreateMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/DeleteMeetingDialog/DeleteMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/DeleteMeetingDialog/language-generation/en-us/DeleteMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/FindSingleContactDialog.dialog, skills/declarative/calendarskill/dialogs/GetContactRequest/GetContactRequest.dialog, skills/declarative/calendarskill/dialogs/GetContactRequest/language-generation/en-us/GetContactRequest.en-us.lg, skills/declarative/calendarskill/dialogs/GetMeetingRequest/GetMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/GetMeetingRequest/language-generation/en-us/GetMeetingRequest.en-us.lg, skills/declarative/calendarskill/dialogs/SearchMeetings/SearchMeetings.dialog, skills/declarative/calendarskill/dialogs/SearchMeetings/language-generation/en-us/SearchMeetings.en-us.lg, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-understanding/en-us/ShowMeetingDialog.en-us.lu, skills/declarative/calendarskill/dialogs/UpdateMeetingDialog/UpdateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/UpdateMeetingDialog/language-generation/en-us/UpdateMeetingDialog.en-us.lg, skills/declarative/calendarskill/language-generation/en-us/common.en-us.lg, skills/declarative/calendarskill/settings/appsettings.json
=> [Calendar] reuse some action and add read meeting logic

skills/declarative/calendarskill/dialogs/CreateMeetingDialog/language-understanding/en-us/CreateMeetingDialog.en-us.lu, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/FindSingleContactDialog.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/language-generation/en-us/FindSingleContactDialog.en-us.lg, skills/declarative/calendarskill/dialogs/GetMeetingRequest/GetMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/SetContent/language-understanding/en-us/SetContent.en-us.lu, skills/declarative/calendarskill/dialogs/SetDateTime/SetDateTime.dialog, skills/declarative/calendarskill/dialogs/SetDateTime/language-understanding/en-us/SetDateTime.en-us.lu, skills/declarative/calendarskill/dialogs/SetDuration/language-understanding/en-us/SetDuration.en-us.lu, skills/declarative/calendarskill/dialogs/SetLocation/language-understanding/en-us/SetLocation.en-us.lu, skills/declarative/calendarskill/dialogs/SetTitle/language-understanding/en-us/SetTitle.en-us.lu, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-understanding/en-us/ShowMeetingDialog.en-us.lu, skills/declarative/calendarskill/language-generation/en-us/common.en-us.lg, skills/declarative/calendarskill/language-understanding/en-us/calendarskill.en-us.lu
add search meeting detail and contact choice
=> [Calendar] add search meeting detail and contact choice

skills/declarative/calendarskill/calendarskill.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/FindSingleContactDialog.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/language-generation/en-us/FindSingleContactDialog.en-us.lg, skills/declarative/calendarskill/dialogs/GetMeetingRequest/GetMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg, skills/declarative/calendarskill/language-generation/en-us/common.en-us.lg, skills/declarative/calendarskill/language-understanding/en-us/calendarskill.en-us.lu, skills/declarative/calendarskill/settings/appsettings.json, skills/declarative/todoskill/dialogs/DeleteToDo/DeleteToDo.dialog, skills/declarative/todoskill/dialogs/DeleteToDo/language-generation/en-us/DeleteToDo.en-us.lg, skills/declarative/todoskill/dialogs/MarkToDo/MarkToDo.dialog, skills/declarative/todoskill/dialogs/MarkToDo/language-generation/en-us/MarkToDo.en-us.lg
support "what is my next meeting"
"Where is my next meeting"
"How long is my next meeting"
...
=> [Calendar] Support show next meeting and ask parameter

skills/declarative/todoskill/BotDesign.md, skills/declarative/todoskill/ToDoSkill.dialog, skills/declarative/todoskill/dialogs/AddToDo/AddToDo.dialog, skills/declarative/todoskill/dialogs/AddToDo/language-generation/en-us/AddToDo.en-us.lg, skills/declarative/todoskill/dialogs/AddToDo/language-understanding/en-us/AddToDo.en-us.lu, skills/declarative/todoskill/dialogs/CorrectPage/CorrectPage.dialog, skills/declarative/todoskill/dialogs/DeleteToDo/DeleteToDo.dialog, skills/declarative/todoskill/dialogs/DeleteToDo/language-generation/en-us/DeleteToDo.en-us.lg, skills/declarative/todoskill/dialogs/DeleteToDo/language-understanding/en-us/DeleteToDo.en-us.lu, skills/declarative/todoskill/dialogs/GetInputListType/GetInputListType.dialog, skills/declarative/todoskill/dialogs/GetInputListType/language-generation/en-us/GetInputListType.en-us.lg, skills/declarative/todoskill/dialogs/GetInputTaskContent/GetInputTaskContent.dialog, skills/declarative/todoskill/dialogs/GetInputTaskContent/language-generation/en-us/GetInputTaskContent.en-us.lg, skills/declarative/todoskill/dialogs/MarkToDo/MarkToDo.dialog, skills/declarative/todoskill/dialogs/MarkToDo/language-generation/en-us/MarkToDo.en-us.lg, skills/declarative/todoskill/dialogs/MarkToDo/language-understanding/en-us/MarkToDo.en-us.lu, skills/declarative/todoskill/dialogs/ShowToDo/ShowToDo.dialog, skills/declarative/todoskill/dialogs/ShowToDo/language-generation/en-us/ShowToDo.en-us.lg, skills/declarative/todoskill/settings/appsettings.json
Update from a branch with tests. Sadly all commits are squashed..
=> [DToDo] various updates

skills/declarative/whoskill/dialogs/ProcessSearchKeywordResult/ProcessSearchKeywordResult.dialog, skills/declarative/whoskill/dialogs/ProcessSearchKeywordResult/language-generation/en-us/ProcessSearchKeywordResult.en-us.lg, skills/declarative/whoskill/dialogs/SearchForFinalResult/SearchForFinalResult.dialog, skills/declarative/whoskill/dialogs/SearchForFinalResult/language-generation/en-us/SearchForFinalResult.en-us.lg, skills/declarative/whoskill/dialogs/SearchPerson/SearchPerson.dialog, skills/declarative/whoskill/dialogs/SearchPerson/language-generation/en-us/SearchPerson.en-us.lg, skills/declarative/whoskill/dialogs/ShowItem/ShowItem.dialog, skills/declarative/whoskill/dialogs/ShowItem/language-generation/en-us/ShowItem.en-us.lg, skills/declarative/whoskill/dialogs/ShowList/ShowList.dialog, skills/declarative/whoskill/dialogs/ShowList/language-generation/en-us/ShowList.en-us.lg, skills/declarative/whoskill/dialogs/ShowNext/ShowNext.dialog, skills/declarative/whoskill/dialogs/ShowNext/language-generation/en-us/ShowNext.en-us.lg, skills/declarative/whoskill/dialogs/ShowPrevious/ShowPrevious.dialog, skills/declarative/whoskill/dialogs/ShowPrevious/language-generation/en-us/ShowPrevious.en-us.lg, skills/declarative/whoskill/language-generation/en-us/whoskill.en-us.lg, skills/declarative/whoskill/whoskill.dialog
=> [WhoSkill] update to latest schema

skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/AcceptMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/CreateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/language-generation/en-us/CreateMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/CreateMeetingRequest/CreateMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/FindSingleContactDialog.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/language-generation/en-us/FindSingleContactDialog.en-us.lg, skills/declarative/calendarskill/dialogs/GetFocusedMeeting/GetFocusedMeeting.dialog, skills/declarative/calendarskill/dialogs/GetMeetingRequest/GetMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg
1. unit naming format
2. return user's name in find contact dialog
3. add tollnumber of meeting
=> [Calendar] fix some issue

skills/declarative/calendarskill/dialogs/FindSingleContactDialog/FindSingleContactDialog.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/language-generation/en-us/FindSingleContactDialog.en-us.lg, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/language-understanding/en-us/FindSingleContactDialog.en-us.lu, skills/declarative/calendarskill/settings/appsettings.json
=> [Calendar] add find contact paging

skills/declarative/calendarskill/dialogs/FindSingleContactDialog/FindSingleContactDialog.dialog, skills/declarative/calendarskill/dialogs/FindSingleContactDialog/language-generation/en-us/FindSingleContactDialog.en-us.lg, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg
1. Fix find contact bug when contact not found.
2. Fix show meeting bug when confirm prompt not recognized.
=> Fix calendar skill bug

skills/declarative/todoskill/BotDesign.md, skills/declarative/todoskill/ToDoSkill.dialog, skills/declarative/todoskill/dialogs/CorrectListType/CorrectListType.dialog, skills/declarative/todoskill/dialogs/CorrectListType/language-generation/en-us/CorrectListType.en-us.lg, skills/declarative/todoskill/dialogs/ShowToDo/ShowToDo.dialog, skills/declarative/todoskill/dialogs/ShowToDo/language-generation/en-us/ShowToDo.en-us.lg, skills/declarative/todoskill/dialogs/ShowToDo/language-understanding/en-us/ShowToDo.en-us.lu, skills/declarative/todoskill/language-generation/en-us/common.en-us.lg, skills/declarative/todoskill/settings/appsettings.json
Tests are in branch hualxie/dtodo-test
=> [DToDo]  add show action for PVA except for tests

skills/declarative/todoskill/BotDesign.md, skills/declarative/todoskill/ToDoSkill.dialog, skills/declarative/todoskill/dialogs/AddToDo/AddToDo.dialog, skills/declarative/todoskill/dialogs/AddToDo/language-generation/en-us/AddToDo.en-us.lg, skills/declarative/todoskill/dialogs/DeleteToDo/DeleteToDo.dialog, skills/declarative/todoskill/dialogs/EndAction/EndAction.dialog, skills/declarative/todoskill/dialogs/EndAction/language-generation/en-us/EndAction.en-us.lg, skills/declarative/todoskill/dialogs/GetToDosOutlook/GetToDosOutlook.dialog, skills/declarative/todoskill/dialogs/MarkToDo/MarkToDo.dialog, skills/declarative/todoskill/dialogs/MatchInList/MatchInList.dialog, skills/declarative/todoskill/dialogs/ShowToDo/ShowToDo.dialog, skills/declarative/todoskill/dialogs/ShowToDo/language-generation/en-us/ShowToDo.en-us.lg, skills/declarative/todoskill/dialogs/StartAction/StartAction.dialog, skills/declarative/todoskill/dialogs/StartAction/language-generation/en-us/StartAction.en-us.lg, skills/declarative/todoskill/language-generation/en-us/common.en-us.lg
Add AddToDo, Delete, Mark actions
=> [DToDo] add remaining actions

skills/declarative/calendarskill/calendarskill.dialog, skills/declarative/calendarskill/dialogs/ConnectToMeeting/language-generation/en-us/ConnectToMeeting.en-us.lg, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg
use expressions to reduce steps
use expressions to reduce steps
=> [Calendar] use expressions to reduce steps

skills/csharp/experimental/bingsearchskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/eventskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponses.lg, skills/csharp/experimental/hospitalityskill/Responses/RequestItem/RequestItemResponsesTexts.lg, skills/csharp/experimental/hospitalityskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/itsmskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/phoneskill/PhoneSkill.csproj, skills/csharp/experimental/phoneskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/restaurantbookingskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/experimental/weatherskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponses.lg, skills/csharp/pointofinterestskill/Responses/Shared/POISharedResponsesTexts.lg, skills/csharp/pointofinterestskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/tests/automotiveskill.tests/Flow/AutomotiveSkillTestBase.cs, skills/csharp/tests/calendarskill.tests/Flow/CalendarSkillTestBase.cs, skills/csharp/tests/emailskill.tests/Flow/EmailSkillTestBase.cs, skills/csharp/tests/musicskill.Tests/SkillTestBase.cs, skills/csharp/tests/phoneskill.tests/PhoneSkill.Tests.csproj, skills/csharp/tests/pointofinterestskill.tests/Flow/PointOfInterestSkillTestBase.cs, skills/csharp/tests/todoskill.tests/Flow/ToDoSkillTestBase.cs, skills/csharp/tests/weatherSkill.tests/Flow/WeatherSkillTestBase.cs, skills/csharp/todoskill/Dialogs/ToDoSkillDialogBase.cs, skills/csharp/todoskill/Responses/DeleteToDo/DeleteToDoResponses.cs, skills/csharp/todoskill/Responses/Shared/ToDoSharedResponses.cs
Update & workaround for ExpandTemplate
=> [Skills] fixes for ExpandTemplate

skills/csharp/experimental/weatherskill/Startup.cs
Fix https://github.com/microsoft/botframework-skills/issues/182
=> [Weather Skill] Fix telemetry config

skills/csharp/pointofinterestskill/Dialogs/MainDialog.cs, skills/csharp/pointofinterestskill/Dialogs/PointOfInterestDialogBase.cs, skills/csharp/pointofinterestskill/Models/ComcastPointOfInterestResponse.cs, skills/csharp/pointofinterestskill/Models/PointOfInterestSkillState.cs, skills/csharp/pointofinterestskill/Utilities/LocaleTemplateManagerWrapper.cs, skills/csharp/shared/SkillServiceLibrary/Models/AzureMaps/SearchAddress.cs, skills/csharp/shared/SkillServiceLibrary/Models/PointofInterestModel.cs, skills/csharp/shared/SkillServiceLibrary/Services/AzureMapsAPI/PointOfInterestModelEx.cs
=> Added city name in return object to Comcast

skills/hackathon/GithubReportAssistant/dialogs/StartNotification/StartNotification.dialog, skills/hackathon/GithubReportAssistant/dialogs/StartNotification/language-generation/en-us/StartNotification.en-us.lg, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/Actions/GithubNotification.cs, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/Actions/ManageNotification.cs, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/ManageNotificationRegistration.cs, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/Middlewares/UserReferenceMiddleware.cs, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/Models/UserReferenceState.cs, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/Schemas/Actions/GithubNotification.schema, skills/hackathon/GithubReportAssistant/extensions/Microsoft.Bot.Solutions.Extensions/Schemas/Actions/ManageNotification.schema, skills/hackathon/GithubReportAssistant/runtime/azurewebapp/Startup.cs, skills/hackathon/GithubReportAssistant/schemas/sdk.schema
Note that
1. help's lg is not submitted
=> add ToBot, GithubNotification action

skills/declarative/calendarskill/runtime/ComposerRuntime.sln
=> [DCalendar] fix extension path

tools/scripts/run_declarative_tests.ps1
=> add test-result.xml

skills/declarative/calendarskill/dialogs/CreateMeetingDialog/CreateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/language-understanding/en-us/CreateMeetingDialog.en-us.lu, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Actions/GetContacts.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Model/CalendarSkillUserModel.cs
1. remove duplicate users in find contacts result
2. fix get input logic issue
=> [DCalendar] fix find contacts issue and get input issue

skills/csharp/calendarskill/CalendarSkill.csproj, skills/csharp/emailskill/EmailSkill.csproj, skills/csharp/experimental/automotiveskill/AutomotiveSkill.csproj, skills/csharp/experimental/bingsearchskill/BingSearchSkill.csproj, skills/csharp/experimental/eventskill/EventSkill.csproj, skills/csharp/experimental/hospitalityskill/HospitalitySkill.csproj, skills/csharp/experimental/itsmskill/ITSMSkill.csproj, skills/csharp/experimental/musicskill/MusicSkill.csproj, skills/csharp/experimental/newsskill/NewsSkill.csproj, skills/csharp/experimental/phoneskill/PhoneSkill.csproj, skills/csharp/experimental/restaurantbookingskill/RestaurantBookingSkill.csproj, skills/csharp/experimental/weatherskill/WeatherSkill.csproj, skills/csharp/pointofinterestskill/PointOfInterestSkill.csproj, skills/csharp/shared/SkillServiceLibrary/SkillServiceLibrary.csproj, skills/csharp/todoskill/ToDoSkill.csproj
Update the microsoft.bot.solution package to 1.0.1
=> update solution package to latest

skills/declarative/calendarskill/dialogs/CreateMeetingDialog/CreateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/language-understanding/en-us/CreateMeetingDialog.en-us.lu, skills/declarative/calendarskill/runtime/ComposerRuntime.sln, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Actions/GetContacts.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Model/CalendarSkillUserModel.cs, tools/scripts/run_declarative_tests.ps1
=> not use DeclarativeTest

skills/declarative/calendarskill/schemas/sdk.schema
=> [DCalendar] update calendar schema

skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Actions/GetContacts.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Model/CalendarSkillUserModel.cs
=> fix user id missing issue

skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg
=> [DCalendar] remove blank line in show meeting lg

skills/declarative/calendarskill/dialogs/CreateMeetingRequest/CreateMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/GetPhotoRequest/GetPhotoRequest.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/language-generation/en-us/ShowMeetingDialog.en-us.lg, skills/declarative/calendarskill/runtime/azurewebapp/Schemas/sdk.schema, skills/declarative/calendarskill/schemas/sdk.schema, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Actions/GetMeetings.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Model/MeetingModel.cs
related issue #189 , and pr #261 
add teams link in CreateMeeting and show it in ShowMeeting
=> [DCalendar] add/show teams link

skills/declarative/calendarskill/language-generation/en-us/common.en-us.lg
=> [DCalendar] fix lg error

skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/language-generation/en-us/AcceptMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/DeleteMeetingDialog/language-generation/en-us/DeleteMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/UpdateMeetingDialog/language-generation/en-us/UpdateMeetingDialog.en-us.lg
1. fix endless loop in show meeting dialog
2. remove useless escape character in lg
=> [DCalendar] Fix calendar dialog and lg issue

skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/AcceptMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/AcceptMeetingDialog/language-generation/en-us/AcceptMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/ConnectToMeetingDialog/ConnectToMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/ConnectToMeetingDialog/language-generation/en-us/ConnectToMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/DeleteMeetingDialog/DeleteMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/SearchMeetings/SearchMeetings.dialog, skills/declarative/calendarskill/dialogs/SearchMeetings/language-generation/en-us/SearchMeetings.en-us.lg, skills/declarative/calendarskill/dialogs/SearchMeetings/language-understanding/en-us/SearchMeetings.en-us.lu
fix some bug found during test
=> [DCalendar] fix calendar bugs

skills/declarative/calendarskill/dialogs/ShowMeetingDialog/ShowMeetingDialog.dialog
=> [DCalendar] fix expression in show meeting dialog

skills/declarative/calendarskill/calendarskill.dialog, skills/declarative/calendarskill/dialogs/BookMeetingRoomDialog/BookMeetingRoomDialog.dialog, skills/declarative/calendarskill/dialogs/BookMeetingRoomDialog/language-generation/en-us/BookMeetingRoomDialog.en-us.lg, skills/declarative/calendarskill/dialogs/CheckPersonAvailableDialog/CheckPersonAvailableDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/CreateMeetingDialog.dialog, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/language-generation/en-us/CreateMeetingDialog.en-us.lg, skills/declarative/calendarskill/dialogs/CreateMeetingDialog/language-understanding/en-us/CreateMeetingDialog.en-us.lu, skills/declarative/calendarskill/dialogs/CreateMeetingRequest/CreateMeetingRequest.dialog, skills/declarative/calendarskill/dialogs/FindMeetingRoom/FindMeetingRoom.dialog, skills/declarative/calendarskill/dialogs/FindMeetingRoom/language-generation/en-us/FindMeetingRoom.en-us.lg, skills/declarative/calendarskill/dialogs/FindMeetingRoom/language-understanding/en-us/FindMeetingRoom.en-us.lu, skills/declarative/calendarskill/dialogs/SearchMeetingRoomReqeust/SearchMeetingRoomReqeust.dialog, skills/declarative/calendarskill/runtime/azurewebapp/Schemas/sdk.schema, skills/declarative/calendarskill/runtime/azurewebapp/Startup.cs, skills/declarative/calendarskill/schemas/sdk.schema, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Actions/GetMeetingRooms.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/AzureSearchComponentRegistration.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/MSGraphComponentRegistration.cs, skills/declarative/extensions/Microsoft.Bot.Solutions.Extensions/Schemas/Actions/Microsoft.AzureSearch.Calendar.GetMeetingRooms.schema
fix bugs and change book meeting room search logic.
=> [DCalendar]fix bugs

skills/csharp/experimental/itsmskill/appsettings.json
=> Fix Appsettings Build Break in ITSMSkill

skills/csharp/emailskill/Responses/Shared/ResponsesAndTexts.de-de.lg, skills/csharp/emailskill/Responses/Shared/ResponsesAndTexts.es-es.lg, skills/csharp/emailskill/Responses/Shared/ResponsesAndTexts.fr-fr.lg, skills/csharp/emailskill/Responses/Shared/ResponsesAndTexts.it-it.lg, skills/csharp/emailskill/Responses/Shared/ResponsesAndTexts.zh-cn.lg, skills/csharp/emailskill/Responses/Shared/SharedTexts.it-it.lg, skills/csharp/emailskill/Utilities/EmailCommonPhrase.cs
fix and close:
https://github.com/microsoft/botframework-skills/issues/274
https://github.com/microsoft/botframework-skills/issues/275
https://github.com/microsoft/botframework-skills/issues/276
=> [Email] fix email issue

skills/csharp/calendarskill/Responses/Card/Card.lg
fix user photo doesn't display in meeting list card issue
=> [Calendar] fix display issue of user photo in meeting list card

.github/ISSUE_TEMPLATE/-net-sdk-bug.md, .github/ISSUE_TEMPLATE/-net-sdk-feature-request.md, .github/ISSUE_TEMPLATE/-net-sdk-question.md
=> Update to SDK issue templates

skills/csharp/calendarskill/readme.md, skills/csharp/emailskill/readme.md, skills/csharp/pointofinterestskill/readme.md, skills/csharp/todoskill/readme.md
=> remove blank line

skills/csharp/tests/todoskill.tests/Flow/GeneralSkillFlowTests.cs, skills/csharp/tests/todoskill.tests/Flow/Utterances/GeneralTestUtterances.cs, skills/csharp/todoskill/Bots/DefaultActivityHandler.cs, skills/csharp/todoskill/Dialogs/MainDialog.cs, skills/csharp/todoskill/Properties/launchSettings.json
Fix help.
Before
After
add Test_Help
=> fix help and add Test_Help

skills/declarative/calendarSkill/dialogs/CreateEventDialog/CreateEventDialog.dialog, skills/declarative/calendarSkill/dialogs/CreateEventDialog/language-generation/en-us/CreateEventDialog.en-us.lg, skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog
fix feedback 7-9 in https://github.com/microsoft/botframework-skills/issues/332
the click is not working issue in 7 can not repro in emulator. will investigate the difference between emulator and teams
1. fix items showing issue in list dialog
2. remove useless logic in create flow
=> [Calendar v2] tune create flow

skills/declarative/calendarSkill/calendarskill.dialog, skills/declarative/calendarSkill/dialogs/CancelEventDialog/CancelEventDialog.dialog, skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog, skills/declarative/calendarSkill/dialogs/RespondToEventDialog/RespondToEventDialog.dialog, skills/declarative/calendarSkill/dialogs/SearchEventsDialog/SearchEventsDialog.dialog, skills/declarative/calendarSkill/dialogs/SearchEventsDialog/language-generation/en-us/SearchEventsDialog.en-us.lg, skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/AcceptEvent.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/CancelEvent.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/CancelEventNotOrganizer.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/DeclineEvent.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/GetEventLocationByAttendees.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/GetEventLocationOnlineMeeting.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/GetEventTitleByAttendees.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/GetEventTitleNoResult.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/GetEventTitleReprompt.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/GetEventTitleWithoutCondition.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/HttpRequestMock/getEventsOnlineMeeting.mock.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/TentativelyAcceptEvent.test.dialog, skills/declarative/calendarSkill/runtime/tests/CalendarSkillTests/DialogTests/cachedResponses/calendarskill_en_us_lu/4218861593.json, skills/declarative/calendarSkill/runtime/tests/DialogTests.cs
=> [CalendarV2] fix bugs

skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog, skills/declarative/calendarSkill/dialogs/SearchEventsDialog/SearchEventsDialog.dialog, skills/declarative/calendarSkill/dialogs/SearchEventsDialog/language-generation/en-us/SearchEventsDialog.en-us.lg, skills/declarative/calendarSkill/dialogs/SearchEventsDialog/language-understanding/en-us/SearchEventsDialog.en-us.lu, skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg
=> [CalendarV2] 

skills/declarative/calendarSkill/dialogs/CreateEventDialog/CreateEventDialog.dialog, skills/declarative/calendarSkill/dialogs/GetContactDialog/GetContactDialog.dialog, skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog, skills/declarative/calendarSkill/dialogs/ListDialog/language-generation/en-us/ListDialog.en-us.lg, skills/declarative/calendarSkill/language-generation/en-us/contactList.en-us.lg, skills/declarative/calendarSkill/language-generation/en-us/timeSuggestionList.en-us.lg
=> [Calendar v2] fix create flow bugs

skills/declarative/calendarSkill/dialogs/GetContactDialog/GetContactDialog.dialog, skills/declarative/calendarSkill/dialogs/GetContactDialog/language-generation/en-us/GetContactDialog.en-us.lg, skills/declarative/calendarSkill/dialogs/ListDialog/ListDialog.dialog, skills/declarative/calendarSkill/language-generation/en-us/contactList.en-us.lg
=> [Calendar v2] fix contact synonyms

skills/declarative/calendarSkill/dialogs/CreateEventDialog/CreateEventDialog.dialog, skills/declarative/calendarSkill/dialogs/CreateEventDialog/language-understanding/en-us/CreateEventDialog.en-us.lu, skills/declarative/calendarSkill/dialogs/UpdateEventDialog/UpdateEventDialog.dialog, skills/declarative/calendarSkill/dialogs/UpdateEventDialog/language-understanding/en-us/UpdateEventDialog.en-us.lu
=> [Calendar v2] fix bugs

skills/declarative/calendarSkill/calendarskill.dialog, skills/declarative/calendarSkill/language-generation/en-us/calendarskill.en-us.lg, skills/declarative/calendarSkill/language-understanding/en-us/calendarskill.en-us.lu, skills/declarative/calendarSkill/settings/cross-train.config.json
close #335
After I added the bot into a group chat, it will shows the button "Launch". And after I click the button, a personal chat will start.
=> [CalendarV2] whisper

skills/declarative/calendarSkill/dialogs/CreateEventDialog/language-generation/en-us/CreateEventDialog.en-us.lg, skills/declarative/calendarSkill/dialogs/SearchEventsDialog/language-understanding/en-us/SearchEventsDialog.en-us.lu, skills/declarative/calendarSkill/dialogs/UpdateEventDialog/UpdateEventDialog.dialog, skills/declarative/calendarSkill/dialogs/UpdateEventDialog/language-generation/en-us/UpdateEventDialog.en-us.lg, skills/declarative/calendarSkill/dialogs/UpdateSlots/UpdateSlots.dialog, skills/declarative/calendarSkill/dialogs/UpdateSlots/language-generation/en-us/UpdateSlots.en-us.lg, skills/declarative/calendarSkill/dialogs/UpdateSlots/language-understanding/en-us/UpdateSlots.en-us.lu, skills/declarative/calendarSkill/language-generation/en-us/event.en-us.lg
fix https://github.com/microsoft/botframework-components/issues/406
fix card disappeared issue https://github.com/microsoft/botframework-components/issues/408
fix duplicate card issue https://github.com/microsoft/botframework-components/issues/409
=> [Calendar v2] fix update dialog issue

experimental/feeds/components.json
add preview js package to the feed
=> add sample js component

skills/declarative/calendarSkill/dialogs/ResolveDateTimeDialog/ResolveDateTimeDialog.dialog, skills/declarative/calendarSkill/dialogs/UpdateEventDialog/UpdateEventDialog.dialog, skills/declarative/calendarSkill/language-generation/en-us/common.en-us.lg
fix https://github.com/microsoft/botframework-components/issues/409
=> [Calendar v2] fix update issue

.gitignore, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/AcceptEvent.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/BaseMsGraphCustomAction.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/CheckAvailability.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/CreateEvent.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/DeclineEvent.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/DeleteEvent.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/FindAvailableTime.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/FindMeetingTimes.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetContacts.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetEventById.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetEvents.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetProfile.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GetWorkingHours.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/GroupEventsByDate.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/TentativelyAcceptEvent.cs, skills/declarative/calendarSkill/runtime/customaction/Actions/MSGraph/UpdateEvent.cs, skills/declarative/calendarSkill/runtime/customaction/MSGraphClient.cs, skills/declarative/calendarSkill/runtime/customaction/MSGraphComponentRegistration.cs, skills/declarative/calendarSkill/runtime/customaction/Models/CalendarSkillContactModel.cs, skills/declarative/calendarSkill/runtime/customaction/Models/CalendarSkillEventModel.cs, skills/declarative/calendarSkill/runtime/customaction/Models/CalendarSkillTimeSlotModel.cs
Refactor MS Graph related code to use common base class and eliminate component registration requirement via attribute on the custom action
- All the MS Graph calls are now internal to the base class
- Consumer of the base class would override a single method to return the result (logging, error handling are also in base class now)
- New ComponentRegistration attribute to automate registration of the custom action in the runtime
It's a refactor
No
=> Refactor MS Graph code in Calendar skill v2

experimental/components/ConversationalCore/ConversationalCore.nuspec, experimental/components/ConversationalCore/language-understanding/en-us/assistant.en-us.lu, experimental/components/ConversationalCore/runtime/azurewebapp/Microsoft.BotFramework.Composer.WebApp.csproj
Update conversational core to use latest component packages
=> Updating conversational core and fixing lu triggers for general

.github/workflows/build-and-test.yml
=> Workflow change to ensure running of automations for declarative skills

experimental/templates/generator-preview-calendar-skill/generators/app/index.js
=> Add MsGraph package reference

experimental/templates/generator-preview-calendar-skill/generators/app/index.js
Move to alpha.2 package for CalendarSkill
=> Move to alpha.2 build package

experimental/components/MsGraph/Actions/GetContacts.cs, experimental/components/MsGraph/Microsoft.BotFramework.CustomAction.MsGraph.csproj
=> Move MsGraph custom action to netstandard2.0 by not using ToHashSet()

generators/generator-conversational-core/generators/app/index.js, generators/generator-conversational-core/generators/app/templates/settings/appsettings.json, generators/generator-conversational-core/package.json
These small changes reflect the latest publish  conversational core generator on npm. So after this PR main will have the latest published generator code which should be the norm moving forward
=> Updating the conversational core template generator.

.gitignore
Currently `.gitignore` includes explicitly mentioned /node_modules directories, this should just ignore ALL of those directories.
=> Maintenance: Ignore all /node_modules directories

docs/qnaTemplateReadMe.md
Adding a read me for the qna template in the docs section.
=> Adding readMe for qna template

generators/generator-conversational-core/package.json
Update conversational core to latest runtime package
=> update runtime version for conversational core

build/yaml/templates/npm-package-steps.yml
Close #565 
- After speaking with Josh, updating Node version from 10.x to 14.x (LTS)
n/a
=> Update JS pipelines to use NPM 14.x

generators/generator-microsoft-bot-conversational-core/generators/app/index.js, generators/generator-multibot/generators/app/index.js, generators/generator-multibot/generators/app/templates/settings/appsettings.json, generators/generator-preview-calendar-skill/generators/app/index.js, generators/generator-preview-calendar-skill/generators/app/templates/settings/appsettings.json
Updating all package references and plugin definitions across our yeoman generators to point to latest packages.
- Updating package references for all generators to latest Microsoft.Bot.Components.* packages published.
- Updating plugin definitions in appsettings.json as well as generator logic to correct references.
N/A
=> feat: Generator package reference updates

build/yaml/pipelines/generator-microsoft-bot-adaptive.yml, build/yaml/pipelines/generator-microsoft-bot-conversational-core.yml, build/yaml/pipelines/generator-microsoft-bot-empty.yml, build/yaml/templates/npm-package-steps.yml, build/yaml/templates/versioning-steps.yml, generators/generator-microsoft-bot-adaptive/package.json, generators/generator-microsoft-bot-conversational-core/generators/app/index.js, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/generators/app/index.js, generators/generator-microsoft-bot-empty/package.json
Generator build YAML files need to be updated to point to renamed generators, and also modify slightly the version suffix to follow pattern set by other SDK packages consistently. Also updating package dependencies for generator-microsoft-bot-conversational-core and generator-microsoft-bot-empty to use generator-microsoft-bot-adaptive.
See above.
Flying by the seat of my pants to be honest.
=> feat: Generator build YAML updates and dependency changes

generators/generator-microsoft-bot-adaptive/package.json, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/package.json, generators/generator-multibot/generators/app/index.js, generators/generator-multibot/package.json, generators/generator-preview-calendar-skill/generators/app/index.js, generators/generator-preview-calendar-skill/package.json
Following publishes of conversational-core and empty generators with correct dependencies in place, updating multibot and calendar generators to update various dependencies.
- Reverting change to package version for adaptive, empty and converational-core generator packages.
- Updating dependencies for multibot and calendar generators.
N/A
=> feat: multibot and calendar generator updates

generators/generator-microsoft-bot-conversational-core/generators/app/index.js, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/generators/app/index.js, generators/generator-microsoft-bot-empty/package-lock.json, generators/generator-microsoft-bot-empty/package.json
The generator-microsoft-bot-conversational-core and generator-microsoft-bot-empty Yeoman generators need to be updated to include the right dependencies for pointing to the now published @microsoft/generator-microsoft-bot-adaptive npm package.
- Updating package.json for both generators to add @microsoft/ prefix to generator dependencies.
- Updating index.js to add @microsoft/ prefix to require.resolve statements.
Manually tested.
=> bug: Fix conversational-core and empty generator dependencies

generators/generator-microsoft-bot-calendar/generators/app/index.js, generators/generator-microsoft-bot-calendar/package.json, generators/generator-microsoft-bot-conversational-core/generators/app/index.js, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/package.json, generators/generator-microsoft-bot-multibot/generators/app/index.js, generators/generator-microsoft-bot-multibot/package.json
Updating all Microsoft.Bot.Components.* package references to latest published versions, as well as updating all dependencies on @microsoft/generator-microsoft-bot-adaptive to latest.
- Update package.json dependency on @microsoft/generator-microsoft-bot-adaptive.
- Update Microsoft.Bot.Components.* package references to latest version.
N/A
=> feat: Package reference updates

generators/generator-microsoft-bot-multibot/generators/app/templates/settings/appsettings.json
Restoring appsettings.json to @microsoft/generator-microsoft-bot-multibot.
- Restoring appsettings.json to @microsoft/generator-microsoft-bot-multibot
N/A
=> bug: Restoring appsettings.json for multibot generator

generators/generator-microsoft-bot-multibot/package.json
Updating dependency version for @microsoft/generator-microsoft-bot-calendar in @microsoft/generator-microsoft-bot-multibot generator to latest published.
- Updating dependency version for @microsoft/generator-microsoft-bot-calendar in @microsoft/generator-microsoft-bot-multibot generator to latest published.
N/A
=> feat: @microsoft/generator-microsoft-bot-multibot update

generators/generator-microsoft-bot-multibot/generators/app/templates/recognizers/conversational-core.en-us.lu.dialog
this will fix the multibot generator's default recognizer settings
=> fix: update some values to match latest orchestrator settings

generators/generator-microsoft-bot-calendar/package.json, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/package.json
Updating dependency version on @microsoft/generator-microsoft-bot-adaptive across calendar, conversational-core and empty generators.
- Updating dependency version on @microsoft/generator-microsoft-bot-adaptive across calendar, conversational-core and empty generators.
N/A
=> feat: @microsoft/generator-microsoft-bot-adaptive dependency version update

generators/generator-microsoft-bot-multibot/package.json
Updating @microsoft/generator-microsoft-bot-multibot dependency versions on adaptive and calendar generators.
- Updating @microsoft/generator-microsoft-bot-multibot dependency versions on adaptive and calendar generators.
N/A
=> feat: @microsoft/generator-microsoft-bot-multibot dependency version update

generators/generator-microsoft-bot-calendar/generators/app/index.js, generators/generator-microsoft-bot-calendar/package.json, generators/generator-microsoft-bot-conversational-core/generators/app/index.js, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/package.json
Updating calendar, conversational-core and empty generators to utilize latest component package versions as well as latest adaptive generator.
- Updating calendar, conversational-core and empty generators to utilize latest component package versions as well as latest adaptive generator.
N/A
=> feat: Generator updates

generators/generator-microsoft-bot-multibot/generators/app/index.js, generators/generator-microsoft-bot-multibot/package.json
Updating multibot generator to reference latest adaptive and calendar generators, as well as latest component package versions.
- Updating multibot generator to reference latest adaptive and calendar generators, as well as latest component package versions.
N/A
=> feat: Multibot generator update

packages/Directory.Build.props
Something is corrupted with the copyright char in source which blocks Nuget publishing. Resolved with correct character.
=> Pipelines: Fix copyright char

generators/generator-microsoft-bot-calendar/generators/app/index.js
Updating referenced Microsoft.Bot.Components.Calendar package version in calendar generator.
- Updating referenced Microsoft.Bot.Components.Calendar package version in calendar generator.
N/A
=> feat: Calendar component package version update

generators/generator-microsoft-bot-calendar-assistant/package.json
Updating @microsoft/generator-microsoft-bot-calendar dependency version.
- Updating @microsoft/generator-microsoft-bot-calendar dependency version.
N/A
=> feat: Calendar Assistant generator update

packages/Graph/Actions/BaseMsGraphCustomAction.cs, packages/Graph/Actions/BaseMsGraphCustomActionGeneric.cs, packages/Graph/Actions/User/GetDirectReports.cs, packages/Graph/Actions/User/GetManager.cs, packages/Graph/Actions/User/GetPeers.cs, packages/Graph/Actions/User/GetWorksWith.cs, packages/Graph/MSGraphClient.cs, packages/Graph/Schemas/Microsoft.Graph.User.GetWorksWith.schema, skills/declarative/whoSkill/whoSkill/schemas/sdk.schema
- Introduces Application Insight-based monitoring for logs/events from the custom action
- Add error handling for NotFound in manager/directreports/peers actions for "top of org chart" scenario
- Added a dependency in Dialog TelemetryClient to log latency and exception detail from the custom action
- Added a new shared HandleException handler for children class to override the base class error handling
- Allow some of the actions in who skills to handle NotFound scenario and return null to denote nothing was found
*Are there any remaining steps or dependencies …
=> MSGraph custom action improvements

skills/declarative/whoSkill/whoSkill/dialogs/ListDialog/ListDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/ListDialog/recognizers/ListDialog.en-us.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/ListDialog/recognizers/ListDialog.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/ListDialog/recognizers/ListDialog.lu.qna.dialog, skills/declarative/whoSkill/whoSkill/dialogs/UnknownIntentDialog/UnknownIntentDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/UnknownIntentDialog/recognizers/UnknownIntentDialog.en-us.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/UnknownIntentDialog/recognizers/UnknownIntentDialog.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/UnknownIntentDialog/recognizers/UnknownIntentDialog.lu.qna.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/WhoIsManagerDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/recognizers/WhoIsManagerDialog.en-us.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/recognizers/WhoIsManagerDialog.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/recognizers/WhoIsManagerDialog.lu.qna.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/WhoIsPersonDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/recognizers/WhoIsPersonDialog.en-us.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/recognizers/WhoIsPersonDialog.lu.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/recognizers/WhoIsPersonDialog.lu.qna.dialog, skills/declarative/whoSkill/whoSkill/language-understanding/en-us/whoSkill.en-us.lu, skills/declarative/whoSkill/whoSkill/recognizers/whoSkill.en-us.lu.dialog, skills/declarative/whoSkill/whoSkill/recognizers/whoSkill.lu.dialog, skills/declarative/whoSkill/whoSkill/recognizers/whoSkill.lu.qna.dialog, skills/declarative/whoSkill/whoSkill/settings/cross-train.config.json, skills/declarative/whoSkill/whoSkill/whoSkill.dialog
- adds who LU and configures triggers and recognizers throughout
=> Add Who LU and configure triggers/recognizers

skills/declarative/whoSkill/whoSkill/dialogs/FindPersonDialog/FindPersonDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/FindPersonDialog/language-generation/en-us/FindPersonDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/UserListDialog/UserListDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/UserListDialog/language-generation/en-us/UserListDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsDirectReportDialog/WhoIsDirectReportDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsDirectReportDialog/language-generation/en-us/WhoIsDirectReportDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/WhoIsManagerDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsManagerDialog/language-generation/en-us/WhoIsManagerDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPeerDialog/WhoIsPeerDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPeerDialog/language-generation/en-us/WhoIsPeerDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/WhoIsPersonDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoWorksWithMeDialog/WhoWorksWithMeDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoWorksWithMeDialog/language-generation/en-us/WhoWorksWithMeDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/language-generation/en-us/whoSkill.en-us.lg, skills/declarative/whoSkill/whoSkill/whoSkill.dialog
Basic flow for finding a user in Who Skill V2 by their name
- Hooked up the GetUsers flow in graph
- Hooked up the find user to the user list dialog flow
=> V0 of Find User in Who Skill V2

generators/generator-microsoft-bot-calendar-assistant/generators/app/index.js, generators/generator-microsoft-bot-calendar-assistant/package.json, generators/generator-microsoft-bot-calendar/generators/app/index.js, generators/generator-microsoft-bot-calendar/package.json, generators/generator-microsoft-bot-command-list/package.json, generators/generator-microsoft-bot-conversational-core/generators/app/index.js, generators/generator-microsoft-bot-conversational-core/package.json, generators/generator-microsoft-bot-empty/package.json, yarn.lock
Updating Calendar, Conversational Core and Calendar Assistant generators to use latest version of published component packages.
- Updating Calendar, Conversational Core and Calendar Assistant generators to use latest version of published component packages.
N/A
=> feat: Generator dependency version updates

skills/declarative/calendarSkill/runtime/customaction/Microsoft.BotFramework.Composer.CustomAction.csproj, skills/declarative/tests/calendarSkill/Microsoft.Bot.CalendarSkill.Dialogs.Tests.csproj, skills/declarative/whoSkill/whoSkill/dialogs/FindPersonDialog/FindPersonDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/UserListDialog/UserListDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsDirectReportDialog/WhoIsDirectReportDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPeerDialog/WhoIsPeerDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPeerDialog/language-generation/en-us/WhoIsPeerDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/WhoIsPersonDialog.dialog, skills/declarative/whoSkill/whoSkill/dialogs/WhoIsPersonDialog/language-generation/en-us/WhoIsPersonDialog.en-us.lg, skills/declarative/whoSkill/whoSkill/dialogs/WhoWorksWithMeDialog/WhoWorksWithMeDialog.dialog, skills/declarative/whoSkill/whoSkill/language-generation/en-us/userList.en-us.lg, skills/declarative/whoSkill/whoSkill/whoSkill.csproj
- Fix bugs around various scenarios in Who skill
- Fix messaging to show the person's name when the have no peers in the org
- Fix csproj build failure when the runtime package was updated
- Handle when the user is not found in the director
- Update Find Person dialog to reflect design
=> Various bug fixes for Who Skill

packages/Welcome/exported/WelcomeDialog/WelcomeDialog.dialog
Minor change missed in previous Welcome PR
=> Welcome: Rename begin dialog event to "BeginDialog"

generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/functions/Triggers/MessagesTrigger.cs
=> Runtime: Functions messages trigger handling InvokeResponse calls.

generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/Controllers/BotController.cs, generators/generator-microsoft-bot-adaptive/generators/app/templates/dotnet/webapp/Controllers/SkillController.cs
=> Added missing using statements to webapp Controllers.

packages/HelpAndCancel/exported/CancelDialog/language-generation/en-us/CancelDialog.en-us.lg, packages/Welcome/exported/WelcomeDialog/language-generation/en-us/WelcomeDialog.en-us.lg
Close #789 which addresses some content tweaks to remove personality
- Publish updated packages after merge
- Update conv core to latest packages
- Add packages to assistant core
=> minor: update HelpAndCancel/Welcome with LG tweaks

generators/generator-bot-assistant-core/generators/app/templates/botName.dialog, generators/generator-bot-calendar-assistant/generators/app/templates/botName.dialog, generators/generator-bot-calendar/generators/app/templates/botName.dialog, generators/generator-bot-command-list/generators/app/templates/botName.dialog, generators/generator-bot-empty/generators/app/templates/botName.dialog, generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog, generators/generator-bot-people/generators/app/templates/botName.dialog, generators/generator-bot-qna-maker/generators/app/templates/botName.dialog, generators/generator-bot-template-generator/app/templates/generators/app/templates/emptyBot.dialog
Fixes #804
Fixed json
Removed extra $designer element
Removed unused $schema property
Note: the botName.dialog file for generator-bot-conversational-core is addressed in another PR.
=> Fixes botName.dialog json

generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/Triggers/SkillsTrigger.cs, generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/Controllers/SkillController.cs
update to depend on ChannelServiceHandlerBase
=> update to depend on ChannelServiceHandlerBase

generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-assistant-core/generators/app/templates/botName.dialog, generators/generator-bot-assistant-core/generators/app/templates/language-understanding/en-us/botName.en-us.lu
#500 Items in Assistant Core
Add package dependency to HelpAndCancel, implement the same root dialog logic as Conversation Core.
=> feat:Add HelpAndCancel to Assistant Core

skills/declarative/whoSkill/whoSkill/whoSkill.dialog
Pass the correct parameter into GetDirectReport intent for the "Teams" button action
=> Fix GetDirectReport intent

packages/HelpAndCancel/exported/CancelDialog/language-generation/en-us/CancelDialog.en-us.lg, packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec, packages/Welcome/exported/WelcomeDialog/WelcomeDialog.dialog, packages/Welcome/exported/WelcomeDialog/language-generation/en-us/WelcomeDialog.en-us.lg
#817 QA pass on HelpAndCancel, Welcome packages
- Added variations for LG responses in CancelDialog
- Imported LG greetings from Assistant Core into Welcome package
- Added missing description to WelcomeDialog and updated description in nuget package
=> feat: Updated HelpAndCancel/Welcome with content from Assistant Core

generators/generator-bot-adaptive/generators/app/index.js, generators/generator-bot-adaptive/generators/app/templates/js/functions/index.js, generators/generator-bot-adaptive/generators/app/templates/js/functions/triggers.js, generators/generator-bot-adaptive/generators/app/templates/js/webapp/index.js
Updates package names and locks versions at 4.13.0-rc0
=> rename and bump js sdk packages

generators/generator-bot-adaptive/generators/app/index.js
Picks up a fix coming for adapter auth/skills auth configuration.
=> bump js sdk to rc2

generators/generator-bot-adaptive/generators/app/index.js
Merging latest changes from main to 4.13.
- Merging latest changes from main to 4.13.
N/A
=> Merge main to 4.13

generators/generator-bot-adaptive/generators/app/index.js, generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-assistant-core/package.json, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar-assistant/package.json, generators/generator-bot-calendar/generators/app/index.js, generators/generator-bot-calendar/package.json, generators/generator-bot-command-list/package.json, generators/generator-bot-conversational-core/generators/app/index.js, generators/generator-bot-conversational-core/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/generators/app/index.js, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-people/generators/app/index.js, generators/generator-bot-people/package.json, generators/generator-bot-qna-maker/package.json, yarn.lock
Updating dependency versions across generators to utilize RC versions of packages.
- Updating dependency versions across generators to utilize RC versions of packages.
=> RC Dependency Version Updates

generators/generator-bot-adaptive/package.json, generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar/generators/app/index.js, generators/generator-bot-conversational-core/generators/app/index.js, generators/generator-bot-enterprise-assistant/generators/app/index.js, generators/generator-bot-people/generators/app/index.js, yarn.lock
Preparing for RC1 publish.
- Merge commit 1cf1c39 from main (see #836).
- Update component dependency versions pre-emptively to RC1.
N/A
=> RC1 Preparation

generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
Use the same version of the Microsoft.Extensions.* used in SDK.  Which isn't the latest.
=> Runtime: Added Azure Functions dependency for user secrets

generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
=> Runtime: Enabled setSpeak by default

generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar/generators/app/index.js, generators/generator-bot-conversational-core/generators/app/index.js, generators/generator-bot-people/generators/app/index.js
Updating component package references in generators to 4.13.0-rc2.
- Updating component package references in generators to 4.13.0-rc2.
N/A
=> Updating component package references in generators to 4.13.0-rc2.

generators/generator-bot-adaptive/generators/app/templates/assets/schemas/readme.md, generators/generator-bot-adaptive/generators/app/templates/assets/schemas/update-schema.ps1, generators/generator-bot-adaptive/generators/app/templates/assets/schemas/update-schema.sh, skills/declarative/calendarSkill/calendarskill/schemas/readme.md, skills/declarative/calendarSkill/calendarskill/schemas/update-schema.ps1, skills/declarative/calendarSkill/calendarskill/schemas/update-schema.sh, skills/declarative/whoSkill/whoSkill/schemas/readme.md, skills/declarative/whoSkill/whoSkill/schemas/update-schema.ps1, skills/declarative/whoSkill/whoSkill/schemas/update-schema.sh
=> Updates to update-schemas

generators/generator-bot-calendar/generators/app/templates/botName.dialog
Fixes broken intents for updating events in calendar generator
=> [RC3] Fix for broken update intents

generators/generator-bot-adaptive/generators/app/templates/assets/schemas/update-schema.ps1, generators/generator-bot-adaptive/generators/app/templates/assets/schemas/update-schema.sh, skills/declarative/calendarSkill/calendarskill/schemas/update-schema.ps1, skills/declarative/calendarSkill/calendarskill/schemas/update-schema.sh, skills/declarative/whoSkill/whoSkill/schemas/update-schema.ps1, skills/declarative/whoSkill/whoSkill/schemas/update-schema.sh
Scripts also now handle csproj and package.json
=> [Cherry Pick 4.13] Change to update-schema script exclusions

generators/generator-bot-adaptive/generators/app/index.js, generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/Startup.cs, generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj, generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/Program.cs, generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj, generators/generator-bot-assistant-core/package.json, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar/package.json, generators/generator-bot-conversational-core/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/generators/app/index.js, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-people/package.json, packages/Graph/Microsoft.Bot.Components.Graph.csproj, packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec, packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec, skills/declarative/Calendar/Calendar/Calendar.csproj, skills/declarative/tests/calendarSkill/Microsoft.Bot.Dialogs.Tests.CalendarSkill.csproj, skills/declarative/tests/common/Microsoft.Bot.Dialogs.Tests.Common.csproj, skills/declarative/tests/whoSkill/Microsoft.Bot.Dialogs.Tests.WhoSkill.csproj, skills/declarative/whoSkill/whoSkill/whoSkill.csproj
Miscellaneous changes being done in preparation for RC3 build for components and generators.
- Update runtime start command for .NET Functions to enable successful running of bot upon scaffolding from Composer.
- Updating SDK package references to 4.13.0-rc4 or equivalent.\
- Updating Program.cs in .NET Web App and Startup.cs in .NET Functions templates to wire through environment name to AddBotRuntimeConfiguration.
- Adding 'msbot-project-template' keyword to generators being supported for R13.
=> Misc RC3 preparation fixes

generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar/generators/app/index.js, generators/generator-bot-conversational-core/generators/app/index.js, generators/generator-bot-people/generators/app/index.js
Updating component dependency versions to 4.13.0-rc3.
- Updating component dependency versions to 4.13.0-rc3.
N/A
=> Updating component dependency versions to 4.13.0-rc3.

generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
Updating appsettings.json to specify new format for **telemetrySettings.
- Updating appsettings.json to specify new format for telemetrySettings.
N/A
=> App Insights update for appsettings.json

generators/generator-bot-adaptive/generators/app/templates/js/functions/host.json, generators/generator-bot-adaptive/generators/app/templates/js/functions/messages/function.json, generators/generator-bot-adaptive/generators/app/templates/js/functions/skills/function.json, generators/generator-bot-adaptive/generators/app/templates/js/functions/static/function.json
- Strips global `api` prefix
- Adds static function binding, defined via https://github.com/microsoft/botbuilder-js/pull/3566
=> fix: bindings so JS functions serves static files

generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar/generators/app/index.js, generators/generator-bot-conversational-core/generators/app/index.js, generators/generator-bot-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc4.
Bumping component dependency versions to 4.13.0-rc4.
N/A
=> Bumping component dependency versions to 4.13.0-rc4.

generators/generator-bot-assistant-core/generators/app/index.js, generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-calendar/generators/app/index.js, generators/generator-bot-conversational-core/generators/app/index.js, generators/generator-bot-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc5.
Bumping component dependency versions to 4.13.0-rc5.
N/A
=> Bumping component dependency versions to 4.13.0-rc5.

generators/generator-bot-adaptive/generators/app/index.js
JS equivalent of https://github.com/microsoft/botframework-components/pull/916/files
=> Adaptive generator: add luis/qna package references

README.md
* Add Teams to Readme
* Update README.md
Co-authored-by: Andrew Clear <1139814+clearab@users.noreply.github.com>
=> [Cherry Pick 4.13] Add Teams to Readme (#921)

generators/generator-bot-adaptive/generators/app/templates/assets/schemas/update-schema.ps1, generators/generator-bot-adaptive/generators/app/templates/assets/schemas/update-schema.sh
Fixes #931 
Added ignore pattern to dialog:merge to ignore files in **/generated
=> Runtime Generator: update-schemas now ignores files in generated.

packages/Graph/Schemas/Microsoft.Graph.Calendar.AcceptEvent.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.CreateEvent.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.DeclineEvent.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.DeleteEvent.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.FindMeetingTimes.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.GetContacts.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.GetEventById.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.GetEvents.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.GetWorkingHours.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FilterEvents.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.FindAvailableTimes.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.GroupEventsByDate.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.Helpers.RecognizeDateTime.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.TentativelyAcceptEvent.uischema, packages/Graph/Schemas/Microsoft.Graph.Calendar.UpdateEvent.uischema, packages/Graph/Schemas/Microsoft.Graph.Photo.GetPhoto.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetDirectReports.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetManager.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetPeers.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetProfile.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetUserProfile.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetUsers.uischema, packages/Graph/Schemas/Microsoft.Graph.User.GetWorksWith.uischema, skills/declarative/whoSkill/whoSkill/schemas/sdk.schema, skills/declarative/whoSkill/whoSkill/schemas/sdk.uischema
Have UISchema for graph package so the custom actions don't all clog up the Custom Actions submenu
Add UISchema to People skill
Tested by merging schema by calling update-schema.ps1 on the UISchema set
Incorporate these back into the template
=> UISchemas for Graph Package

generators/generator-bot-assistant-core/generators/app/templates/botName.dialog, generators/generator-bot-assistant-core/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog, generators/generator-bot-enterprise-assistant/README.md, generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog, generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog
- Fixes #948 
- Fixes #947 
- Added support for interruption on BotTour dialog in EA and Assistant Core
=> [EA] Bot Tour interruption issue and readme fix

generators/generator-bot-calendar/generators/app/templates/README.md, generators/generator-bot-enterprise-assistant/generators/app/templates/README.md, generators/generator-bot-people/generators/app/templates/README.md
Fixes #961 
Updates the authentication setup instructions for EA, Calendar, and People
=> [EA] Update authentication docs

generators/generator-bot-qna-maker/README.md
Updating qna maker read me, the bot that qna created under the hood has the friendly name of 'empty bot', the read me now reflects that.
=> Updating qna read me

generators/generator-bot-calendar-assistant/generators/app/index.js, generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc6.
Bumping component dependency versions to 4.13.0-rc6.
N/A
=> Bumping component dependency versions to 4.13.0-rc6.

.github/workflows/conventional-pr/.gitignore, .github/workflows/conventional-pr/action.yml, .github/workflows/conventional-pr/package.json, .github/workflows/conventional-pr/src/conventional-pr.ts, .github/workflows/conventional-pr/src/utils.ts, .github/workflows/conventional-pr/tsconfig.json
=> chore: import semantic pr action from the bf-composer repo

packages/Teams/Schemas/Actions/Teams.GetMeetingParticipant.uischema, packages/Teams/Schemas/Actions/Teams.GetMember.uischema, packages/Teams/Schemas/Actions/Teams.GetPagedMembers.uischema, packages/Teams/Schemas/Actions/Teams.GetPagedTeamMembers.uischema, packages/Teams/Schemas/Actions/Teams.GetTeamChannels.uischema, packages/Teams/Schemas/Actions/Teams.GetTeamDetails.uischema, packages/Teams/Schemas/Actions/Teams.GetTeamMember.uischema, packages/Teams/Schemas/Actions/Teams.SendAppBasedLinkQueryResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMEActionResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMEAttachmentsResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMEAuthResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMEBotMessagePreviewResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMEConfigQuerySettingUrlResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMEMessageResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMESelectItemResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendMessageToTeamsChannel.uischema, packages/Teams/Schemas/Actions/Teams.SendTabAuthResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendTabCardResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendTaskModuleCardResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendTaskModuleMessageResponse.uischema, packages/Teams/Schemas/Actions/Teams.SendTaskModuleUrlResponse.uischema
Fixes: https://github.com/microsoft/botframework-components/issues/872
=> fix: Teams sub menu updates

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc7.
Bumping component dependency versions to 4.13.0-rc7.
N/A
#minor
=> chore: Bumping component dependency versions to 4.13.0-rc7.

generators/generator-bot-enterprise-assistant/package.json
Closes #1048.
- Adding keyword 'msbot-multibot-project' to @microsoft/generator-bot-enterprise-assistant package.
N/A
=> chore: Add 'msbot-multibot-project' keyword to @microsoft/generator-bot-enterprise-assistant

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc8.
Bumping component dependency versions to 4.13.0-rc8.
N/A
#minor
=> chore: Bumping component dependency versions to 4.13.0-rc8.

build/yaml/templates/npm-versioning-steps.yml
More cherry picks from main to 4.13 for RC8.
See commits below for further details.
N/A
#minor
=> chore: 4.13 RC8 Cherry Picks #2

build/yaml/templates/npm-build-steps.yml
More cherry picks from main to 4.13 for RC8.
See commits below for further details.
N/A
#minor
=> chore: 4.13 RC8 Cherry Picks #3

build/yaml/templates/component-template.yml, packages/Teams/js/package.json, yarn.lock
More cherry picks from main to 4.13 for RC8.
See commits below for further details.
N/A
#minor
=> chore: 4.13 RC8 Cherry Picks #4

generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog
=> fix: Fixed json bug in main dialog of EA

generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj
Fixes #1063.
- Fixing closing tag for local.settings.json Content element in .NET Functions .csproj template.
Verified in published Azure Functions app.
=> fix: Fixing closing tag for local.settings.json Content element in .NET Functions .csproj template

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc9.
Bumping component dependency versions to 4.13.0-rc9.
N/A
#minor
=> chore: Bumping component dependency versions to 4.13.0-rc9.

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-people/generators/app/index.js
Bumping component dependency versions to 4.13.0-rc10.
Bumping component dependency versions to 4.13.0-rc10.
N/A
#minor
=> chore: Bumping component dependency versions to 4.13.0-rc10.

generators/generator-bot-adaptive/generators/app/index.js
=> chore: bump js sdk version to 4.13.2-preview

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-people/generators/app/index.js
Bumping component dependency versions to 4.13.0.
Bumping component dependency versions to 4.13.0.
N/A
#minor
=> chore: Bumping component dependency versions to 4.13.0.

generators/generator-bot-adaptive/generators/app/index.js, generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/Triggers/StaticFilesTrigger.cs, generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj, generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog, generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/CreateEventDialog/language-generation/en-us/CreateEventDialog.en-us.lg, tests/Microsoft.Bot.Components.Tests.sln
Cherry picks from main to 4.13 for RC12.
See commits below for further details.
N/A
#minor
=> chore: 4.13 RC13 Cherry Picks

generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/package.json, generators/generator-bot-core-qna/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/package.json
=> chore: [4.13] Set generator versions to 1.0.0

yarn.lock
=> chore: [4.13] Updated yarn.lock for adaptive generator

.github/labeler.yml
=> chore: PR labeler corrections

generators/generator-bot-adaptive/generators/app/templates/dotnet/functions/botName.csproj, generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/botName.csproj
=> fix: generator-bot-adaptive: Include *.model

generators/generator-bot-adaptive/generators/app/templates/assets/appsettings.json
=> fix: generator-bot-adaptive: Updated default speak voice

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-core-language/package.json, generators/generator-bot-core-qna/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/generators/app/index.js, generators/generator-bot-enterprise-people/package.json, packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj, yarn.lock
Package metadata, including dependency versions, needs to be updated to reflect GA versions as published from 4.13 branch.
- Updating generator package dependencies to use GA versions of other generators.
- Update references to components to use 1.0.0 GA version in generators.
- Aligning tags for Teams package on .NET.
N/A
#minor
=> chore: Update package metadata

packages/AdaptiveCards/Actions/UpdateAdaptiveCard.cs, packages/AdaptiveCards/Schemas/Microsoft.Bot.Components.UpdateAdaptiveCard.schema
Fixes #1153 
Fixes a type and a null reference exception in `AdaptiveCards.UpdateAdaptiveCard` action.
- Fixed a typo in the schema for UpdateAdaptiveCard.
- Fixed a null reference exception in UpdateAdaptiveCard.
=> fix: Stevenic/ac fix

packages/Telephony/Schemas/Microsoft.Telephony.PauseRecording.uischema, packages/Telephony/Schemas/Microsoft.Telephony.ResumeRecording.uischema, packages/Telephony/Schemas/Microsoft.Telephony.StartRecording.uischema
Update the subtitle of recording operations to be more descriptive
Update the subtitle of recording operations to be more descriptive
n/a
#minor
=> chore:Update subtitle for recording operations

generators/generator-bot-adaptive/package.json, generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/package.json, generators/generator-bot-core-qna/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/package.json, yarn.lock
Update package version from 1.0.1 to 1.1.0
Update package version from 1.0.1 to 1.1.0
=> fix: Generator versioning for 4.14

generators/generator-bot-adaptive/platforms.js, generators/generator-bot-adaptive/test/dotnet-functions.test.js, generators/generator-bot-adaptive/test/dotnet-webapp.test.js, generators/generator-bot-enterprise-assistant/generators/app/index.js, packages/AdaptiveCards/Microsoft.Bot.Components.AdaptiveCards.csproj, packages/Graph/Microsoft.Bot.Components.Graph.csproj, packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec, packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj, packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec, skills/csharp/calendarskill/CalendarSkill.csproj, skills/declarative/Calendar/Calendar/Calendar.csproj, skills/declarative/People/People/People.csproj, tests/functional/Libraries/TranscriptConverter/TranscriptConverter.csproj, tests/functional/Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj, tests/unit/skills/calendar/Microsoft.Bot.Dialogs.Tests.Skills.Calendar.csproj, tests/unit/skills/common/Microsoft.Bot.Dialogs.Tests.Common.csproj, tests/unit/skills/people/Microsoft.Bot.Dialogs.Tests.Skills.People.csproj
Update Components branch to final build of 4.14.0 which includes all templates, Graph package, Welcome package, HelpAndCancel package, AdaptiveCard package, Teams package, and dotnet functional tests.
Update Components branch to final build of 4.14.0
=> feat: Update Components branch to final build of 4.14.0 .NET SDK

generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-core-qna/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/generators/app/index.js, generators/generator-bot-enterprise-people/package.json, yarn.lock
Specify to use preview version for templates to consume packages
=> feat: Use preview version for RC/preview releases

generators/generator-bot-adaptive/platforms.js, generators/generator-bot-adaptive/test/dotnet-functions.test.js, generators/generator-bot-adaptive/test/dotnet-webapp.test.js, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-core-qna/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/generators/app/index.js, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/generators/app/index.js, generators/generator-bot-enterprise-people/package.json, packages/AdaptiveCards/Microsoft.Bot.Components.AdaptiveCards.csproj, packages/Graph/Microsoft.Bot.Components.Graph.csproj, packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec, packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj, packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec, skills/csharp/calendarskill/CalendarSkill.csproj, skills/declarative/Calendar/Calendar/Calendar.csproj, skills/declarative/People/People/People.csproj, tests/functional/Libraries/TranscriptConverter/TranscriptConverter.csproj, tests/functional/Libraries/TranscriptTestRunner/TranscriptTestRunner.csproj, tests/unit/packages/Microsoft.Bot.Components.Teams.Tests/Microsoft.Bot.Components.Teams.Tests.csproj, tests/unit/skills/calendar/Microsoft.Bot.Dialogs.Tests.Skills.Calendar.csproj, tests/unit/skills/common/Microsoft.Bot.Dialogs.Tests.Common.csproj, tests/unit/skills/people/Microsoft.Bot.Dialogs.Tests.Skills.People.csproj, yarn.lock
Moving the branch to RC0 and update to use 4.14.1 C# SDK.
=> chore: Moving branch to RC0 + bump C# SDK to 4.14.1

packages/Teams/js/src/conditions/index.ts, tests/unit/packages/Teams/js/package.json, yarn.lock
=> fix: fully remove unnecessary onTeamsMEConfigurationSetting

generators/generator-bot-adaptive/package.json, generators/generator-bot-core-assistant/generators/app/index.js, generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/generators/app/index.js, generators/generator-bot-core-language/package.json, generators/generator-bot-core-qna/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/generators/app/index.js, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/generators/app/index.js, generators/generator-bot-enterprise-people/package.json, packages/AdaptiveCards/Microsoft.Bot.Components.AdaptiveCards.csproj, packages/Graph/Microsoft.Bot.Components.Graph.csproj, packages/HelpAndCancel/Microsoft.Bot.Components.HelpAndCancel.nuspec, packages/HelpAndCancel/package.json, packages/Teams/dotnet/Microsoft.Bot.Components.Teams.csproj, packages/Teams/js/package.json, packages/Welcome/Microsoft.Bot.Components.Welcome.nuspec, packages/Welcome/package.json, yarn.lock
Update the templates and package versions to 1.1.1 after fixes to references from preview to latest versions of the packages/templates.
=> fix: Bump version to 1.1.1 and incorrect references from preview to latest

build/yaml/templates/nuget-versioning-steps.yml
=> ci: NuGet pipeline: revert unintended change from merge

packages/Telephony/Actions/BatchFixedLengthInput.cs, packages/Telephony/Actions/BatchTerminationCharacterInput.cs, packages/Telephony/Common/RegexAggregatorInput.cs, packages/Telephony/Microsoft.Bot.Components.Telephony.csproj, packages/Telephony/Readme.md, packages/Telephony/Schemas/Microsoft.Telephony.FixedLengthBatchInput.schema, packages/Telephony/Schemas/Microsoft.Telephony.FixedLengthBatchInput.uischema, packages/Telephony/Schemas/Microsoft.Telephony.TerminationCharacterBatchInput.schema, packages/Telephony/Schemas/Microsoft.Telephony.TerminationCharacterBatchInput.uischema, packages/Telephony/TelephonyBotComponent.cs, tests/packages/Microsoft.Bot.Components.Telephony.Tests/BatchInputTests.cs, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_FixedLengthBaseScenario.test.dialog, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_FixedLengthHappyPath.test.dialog, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_FixedLengthIgnoresNonDTMF.test.dialog, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_TerminationBaseScenario.test.dialog, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_TerminationHappyPath.test.dialog, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_TerminationIgnoresNonDTMF.test.dialog, tests/packages/Microsoft.Bot.Components.Telephony.Tests/Microsoft.Bot.Components.Telephony.Tests.csproj
Purpose
fixes: microsoft/botframework-telephony#46 (since linking this didn't work I guess it must be #minor ;)
Changes
Added action for DTMF batching. Supports both termination characters and fixed length batches.
Tests
Added happy path tests for new action.
=> feat: DTMF Batching for Telephony package

packages/Telephony/Microsoft.Bot.Components.Telephony.csproj
=> build: Telephony: Update version to 1.0.0 and update SDK dependency to 4.14.1

packages/Telephony/Microsoft.Bot.Components.Telephony.csproj
=> build: Telephony adjustments for pipelines

generators/generator-bot-core-assistant/generators/app/templates/botName.dialog, generators/generator-bot-core-assistant/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog, generators/generator-bot-core-assistant/generators/app/templates/dialogs/ChitchatDialog/ChitchatDialog.dialog, generators/generator-bot-core-assistant/generators/app/templates/dialogs/FeedbackDialog/FeedbackDialog.dialog, generators/generator-bot-core-language/generators/app/templates/botName.dialog, generators/generator-bot-empty/generators/app/templates/botName.dialog, generators/generator-bot-enterprise-assistant/generators/app/templates/botName.dialog, generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/BotTourDialog/BotTourDialog.dialog, generators/generator-bot-enterprise-assistant/generators/app/templates/dialogs/ChitchatDialog/ChitchatDialog.dialog
Adds comments for Empty, Core Asst, Core w Lang, and EA
#minor
=> chore: Added comments for remaining templates

generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/package.json, yarn.lock
- Reference rc3 adaptive bot generator for final validation before GA, will revert this PR after everything passes
#minor
=> chore: fix generator rc reference

packages/Telephony/Actions/BatchFixedLengthInput.cs, packages/Telephony/Actions/BatchRegexInput.cs, packages/Telephony/Actions/BatchTerminationCharacterInput.cs, packages/Telephony/Actions/TimeoutChoiceInput.cs, packages/Telephony/Common/BotWithLookup.cs, packages/Telephony/Common/IStateMatrix.cs, packages/Telephony/Common/LatchingStateMatrix.cs, packages/Telephony/Microsoft.Bot.Components.Telephony.csproj, packages/Telephony/Schemas/Microsoft.Telephony.BatchRegexInput.schema, packages/Telephony/Schemas/Microsoft.Telephony.BatchRegexInput.uischema, packages/Telephony/Schemas/Microsoft.Telephony.TimeoutChoiceInput.schema, packages/Telephony/Schemas/Microsoft.Telephony.TimeoutChoiceInput.uischema, packages/Telephony/TelephonyBotComponent.cs, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/BatchInputTests.cs, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_RegexBaseScenario.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_RegexHappyPath.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_Regex_InterruptionIgnoredForMaskedDigits.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_Regex_WithTangent_InterruptionDisabled.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_Regex_WithTangent_InterruptionEnabled.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_Regex_WithTangent_InterruptionEnabled_EventInterrupt.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/BatchInputTests/BatchInput_Regex_WithTangent_InterruptionEnabled_WithReprompt.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Microsoft.Bot.Components.Telephony.Tests.csproj
Prepares the Telephony package for R15
* flattened regex batching and prompt with timeout changes
* Remove placeholder for timeout tests
Co-authored-by: Autumn Wyborny <auwyb@microsoft.com>
#minor
=> chore: cherry-pick #1287 

generators/generator-bot-enterprise-assistant/generators/app/index.js, yarn.lock
Fixes https://github.com/microsoft/BotFramework-Composer/issues/8927
Globby dependency changed its pattern for excluding files which broken the generation of the .sln file for the Enterprise Assistant Template. This PR resolves that issue
=> fix: bug with globby not excluding files correctly

generators/generator-bot-enterprise-assistant/generators/app/index.js, yarn.lock
Cherry-pick #1293 into 4.15 branch
#minor
=> chore: fixes bug with globby not excluding files correctly (#1293)

generators/generator-bot-adaptive/baseGenerator.js, generators/generator-bot-enterprise-assistant/generators/app/index.js
* make globby exclusion parameter explicit
* run yarn lint fix
Co-authored-by: Ryan Lengel Isgrig <rylengel@microsoft.com>
#minor
=> fix: make globby exclusion parameter explicit (#1299)

generators/generator-bot-enterprise-calendar/generators/app/templates/dialogs/ResolveDateTimeDialog/ResolveDateTimeDialog.dialog, skills/declarative/Calendar/Calendar/dialogs/ResolveDateTimeDialog/ResolveDateTimeDialog.dialog
=> fix: Update ResolveDateTimeDialog.dialog

generators/generator-bot-adaptive/baseGenerator.js
* make globby exclusion parameter explicit
* adjust glob to use cwd parameter isntead of manipulating the path
this caused issues when running inside composer
* fix linting
#minor
=> fix: adjust glob function  (#1303)

generators/generator-bot-enterprise-assistant/package.json
=> chore: bump enterprise assistant generator to 1.2.2

generators/generator-bot-adaptive/package.json, generators/generator-bot-core-assistant/package.json, generators/generator-bot-core-language/package.json, generators/generator-bot-empty/package.json, generators/generator-bot-enterprise-assistant/package.json, generators/generator-bot-enterprise-calendar/package.json, generators/generator-bot-enterprise-people/package.json, yarn.lock
#minor increment to generator versions to consume the globby fix in #1303
=> chore: bump all generators to 1.2.2

packages/Telephony/Actions/CallTransfer.cs, packages/Telephony/Actions/SerialNumberInput.cs, packages/Telephony/Actions/SerialNumberPattern.cs, packages/Telephony/Actions/SerialNumberTextGroup.cs, packages/Telephony/Schemas/Microsoft.Telephony.SerialNumberInput.schema, packages/Telephony/Schemas/Microsoft.Telephony.SerialNumberInput.uischema, packages/Telephony/TelephonyBotComponent.cs, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/SerialNumberInputTests/SerialNumberInput_BaseScenario.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/SerialNumberInputTests/SerialNumberInput_HappyPath.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/Integration/SerialNumberInputTests/SerialNumberInput_WithInterruption.test.dialog, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/SerialNumberInputTests.cs
* Added  SerialNumberPattern classes
Added  SerialNumberPattern classes to post process STT result for serial numbers
* Fixed build warnings
* SerialNumberInput
Reworked SerialNumberPattern
* Added schema/test
* test fixes
* Fixed unit test
* allow personalization of confirmation prompt
* Added SerialNumberInput with intteruption
#minor
=> feat: Serial number post processing for STT (#1300)

generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetCollaboratorsDialog/GetCollaboratorsDialog.dialog, generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetDirectReportsDialog/GetDirectReportsDialog.dialog, generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetPeersDialog/GetPeersDialog.dialog, generators/generator-bot-enterprise-people/generators/app/templates/dialogs/GetUserDialog/GetUserDialog.dialog, generators/generator-bot-enterprise-people/generators/app/templates/dialogs/ListDialog/ListDialog.dialog, packages/Graph/Actions/Event/CreateEvent.cs, packages/Graph/Actions/Event/GetEventById.cs, packages/Graph/Actions/Event/GetEvents.cs, packages/Graph/Actions/Helpers/FindAvailableTimes.cs, packages/Graph/Actions/Helpers/GroupEventsByDate.cs, packages/Graph/Actions/User/FindMeetingTimes.cs, packages/Graph/Models/CalendarSkillEventModel.cs, skills/declarative/People/People/dialogs/GetCollaboratorsDialog/GetCollaboratorsDialog.dialog, skills/declarative/People/People/dialogs/GetDirectReportsDialog/GetDirectReportsDialog.dialog, skills/declarative/People/People/dialogs/GetPeersDialog/GetPeersDialog.dialog, skills/declarative/People/People/dialogs/GetUserDialog/GetUserDialog.dialog, skills/declarative/People/People/dialogs/ListDialog/ListDialog.dialog
Bug fixes for 4.16 release
- Uses invariant culture when parsing datetimes in Graph package
- Updates foreach node properties to be unique to prevent "Bad Request" exceptions
=> Lamil/bug fixes 4.16

generators/generator-bot-adaptive/generators/app/templates/dotnet/webapp/Startup.cs, skills/csharp/calendarskill/Startup.cs, skills/csharp/emailskill/Startup.cs, skills/csharp/experimental/automotiveskill/Startup.cs, skills/csharp/experimental/bingsearchskill/Startup.cs, skills/csharp/experimental/eventskill/Startup.cs, skills/csharp/experimental/hospitalityskill/Startup.cs, skills/csharp/experimental/itsmskill/Startup.cs, skills/csharp/experimental/musicskill/Startup.cs, skills/csharp/experimental/newsskill/Startup.cs, skills/csharp/experimental/phoneskill/Startup.cs, skills/csharp/experimental/restaurantbookingskill/Startup.cs, skills/csharp/experimental/weatherskill/Startup.cs, skills/csharp/pointofinterestskill/Startup.cs, skills/csharp/todoskill/Startup.cs, skills/declarative/Calendar/Calendar/Startup.cs, skills/declarative/People/People/Startup.cs
=> fix: Updated NewtonSoft MaxDepth in Startup to use 128

packages/Telephony/Microsoft.Bot.Components.Telephony.csproj
=> bump: Bumped Telephony version to 1.4.1

.gitignore, packages/Graph/Microsoft.Bot.Components.Graph.csproj, packages/Microsoft.Bot.Components.sln, packages/Recognizers/CustomQuestionAnswering/CustomQuestionAnsweringRecognizerBotComponent.cs, packages/Recognizers/CustomQuestionAnswering/Microsoft.Bot.Components.Recognizers.CustomQuestionAnsweringRecognizer.csproj, packages/Recognizers/CustomQuestionAnswering/QuestionAnswering/CustomQuestionAnsweringRecognizer.cs, packages/Recognizers/CustomQuestionAnswering/README.md, packages/Recognizers/CustomQuestionAnswering/Schemas/Microsoft.Bot.Components.Recognizers.CustomQuestionAnsweringRecognizer.schema, packages/Telephony/Microsoft.Bot.Components.Telephony.csproj
This is the source code for the custom question answering recognizer.
Source code for custom question answering recognizer.
=> feat: CQA recognizers

packages/Recognizers/CustomQuestionAnswering/README.md
Refactors the README for the Custom Question Answering recognizer to add clarity to make it easier for the user to understand how to configure the new recognizer for use in a Composer bot.
Modified and added to the content.
Ran through these steps in Composer 2.1.2 and ended up with a working bot.
N/A
=> docs: Update README for CQA Recognizer

package.json, yarn.lock
Fixes #minor
Vulnerability alert title: Governed repositories microsoft/botframework-components main CVE-2021-37712, CVE-2021-37713, CVE-2021-37701, CVE-2021-32803, CVE-2021-32804
Web page: [FuseLabs](https://fuselabs.visualstudio.com/)/[SDK_v4](https://fuselabs.visualstudio.com/SDK_v4)/[Compliance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)/[Component Governance](https://fuselabs.visualstudio.com/SDK_v4/_componentGovernance/177327)
High severity alert: Arbitrary File Creation, Arbitrary File Overwrite, Arbitrary Code Execution
Upgrade tar from 6.1.0 to 6.1.9
The current PR includes the fixes in these PRs. If you merge this one, you don't need to merge these.
Upgrade to "adal-node": "0.2.4" 
Upgrade to "@xmldom/xmldom": "0.8.6"
Upgrade to "axios": "1.2.1" …
=> fix: Component Governance security vulnerability for tar 6.1.0

packages/Recognizers/CustomQuestionAnswering/js/.eslintrc.json, packages/Recognizers/CustomQuestionAnswering/js/.gitignore, packages/Recognizers/CustomQuestionAnswering/js/README.md, packages/Recognizers/CustomQuestionAnswering/js/package.json, packages/Recognizers/CustomQuestionAnswering/js/schemas/custom-question-answering-recognizer.schema, packages/Recognizers/CustomQuestionAnswering/js/src/CQABotComponent.ts, packages/Recognizers/CustomQuestionAnswering/js/src/CQARecognizer.ts, packages/Recognizers/CustomQuestionAnswering/js/src/index.ts, packages/Recognizers/CustomQuestionAnswering/js/tsconfig.json
This PR includes the CQA Package support for node.js Bots. 
- Ported package using the C# version as a base.
- Added a README file with instructions on how to install and configure the package.
No tests included.
=> port: CQA Package (js version)

build/yaml/pipelines/clu.yml
=> Added CLU recognizer pipeline

packages/Recognizers/ConversationLanguageUnderstanding/dotnet/Microsoft.Bot.Components.Recognizers.CLURecognizer.csproj
=> CLU to SDK 4.19.3

tests/unit/Microsoft.Bot.Components.Tests.sln, tests/unit/packages/Recognizers/dotnet/Microsoft.Bot.Components.Recognizers.CLURecognizer.Tests.Unit.csproj
=> fix: Corrected CLU test paths

packages/Recognizers/ConversationLanguageUnderstanding/dotnet/Schemas/Microsoft.CluRecognizer.schema
=> Corrected CLU schema

build/yaml/templates/dotnet-build-test-steps.yml, build/yaml/templates/dotnet-package-steps.yml, packages/Recognizers/ConversationLanguageUnderstanding/dotnet/Microsoft.Bot.Components.Recognizers.CLURecognizer.csproj
=> Using 3.1.x and 6.0.x

packages/Graph/Microsoft.Bot.Components.Graph.csproj, tests/unit/packages/Teams/dotnet/Microsoft.Bot.Components.Teams.Tests.csproj
=> Dropped netcoreapp2.1

packages/Recognizers/ConversationLanguageUnderstanding/dotnet/README.md
Update the README for the CLU Recognizer to clarify certain points:
* Add a required setting to the JSON
* Clarify where to find the endpoint, and the fact that the trailing slash must be omitted
* Clarify that intent triggers must match the intent
Updated README.md for the CLU Recognizer package.
README now matches the steps required to get a bot using this recognizer working.
N/A
=> docs: Update Dotnet CLU Recognizer README

tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/NuGet.Config, tests/unit/skills/calendar/NuGet.Config, tests/unit/skills/common/NuGet.Config
=> Removed external packages feeds

packages/NuGet.Config
=> Removed external Nuget package source

packages/Recognizers/ConversationLanguageUnderstanding/js/README.md, packages/Recognizers/ConversationLanguageUnderstanding/js/src/index.ts, tests/unit/packages/Recognizers/js/package.json, tests/unit/packages/Recognizers/js/tests/cluApplication.test.ts, tests/unit/packages/Recognizers/js/tests/cluExtensions.test.ts, tests/unit/packages/Recognizers/js/tests/cluRecognizerOptions.test.ts, tests/unit/packages/Recognizers/js/tests/cluRecognizerOptionsBase.test.ts, tests/unit/packages/Recognizers/js/tests/defaultHttpClientFactory.test.ts, yarn.lock
=> Updated CLU package names from previous commit

build/yaml/pipelines/clu-js.yml
=> CLU-JS pipeline change

build/yaml/pipelines/clu-js.yml
=> CLU-JS pipeline image

build/yaml/functional/deployBotResources/dotnet/evaluateDependenciesVariables.yml, packages/NuGet.Config, tests/unit/packages/Microsoft.Bot.Components.Telephony.Tests/NuGet.Config, tests/unit/skills/calendar/NuGet.Config, tests/unit/skills/common/NuGet.Config
=> Updated Components to use SDK_v4 feed
